asbest	asbesten	N;DEF;SG
bukett	buketter	N;NDEF;PL
bukett	buketten	N;DEF;SG
bukett	bukettene	N;DEF;PL
profet	profeter	N;NDEF;PL
profet	profeten	N;DEF;SG
profet	profetene	N;DEF;PL
ubrutt	ubrutte	ADJ;DEF;SG+PL
ubrutt	ubrutt	ADJ;NEUT;SG
spare	sparer	V;PRS
spare	sparende	V.PTCP;PRS
spare	spar	V;IMP
spare	sparte	V;PST
spare	spart	V.PTCP;PST
teddybjørn	teddybjørnen	N;DEF;SG
teddybjørn	teddybjørnene	N;DEF;PL
teddybjørn	teddybjørner	N;NDEF;PL
legitim	legitime	ADJ;DEF;SG+PL
legitim	legitimt	ADJ;NEUT;SG
gjær	gjæren	N;DEF;SG
badekar	badekaret	N;DEF;SG
badekar	badekar	N;NDEF;PL
badekar	badekarene	N;DEF;PL
badekar	badekara	N;DEF;PL
grå	gråere	ADJ;CMPR
grå	grå	ADJ;DEF;SG+PL
grå	grått	ADJ;NEUT;SG
grå	gråeste	ADJ;SPRL;DEF
grå	gråest	ADJ;SPRL;NDEF
strømme	strøm	V;IMP
strømme	strømmer	V;PRS
strømme	strømte	V;PST
strømme	strømmet	V.PTCP;PST
strømme	strømmende	V.PTCP;PRS
strømme	strømma	V;PST
konferere	konferert	V.PTCP;PST
konferere	konfererer	V;PRS
konferere	konfererte	V;PST
konferere	konferer	V;IMP
bensin	bensinen	N;DEF;SG
enkelt	enkelte	ADJ;DEF;SG+PL
enkelt	enkelt	ADJ;NEUT;SG
talgokse	talgokser	N;NDEF;PL
talgokse	talgoksen	N;DEF;SG
talgokse	talgoksene	N;DEF;PL
kinesisk	kinesiske	ADJ;DEF;SG+PL
kinesisk	kinesisk	ADJ;NEUT;SG
kinesisk	kinesisken	N;DEF;SG
kjole	kjolene	N;DEF;PL
kjole	kjolen	N;DEF;SG
kjole	kjoler	N;NDEF;PL
tålmodighet	tålmodigheten	N;DEF;SG
israelitt	israelittene	N;DEF;PL
israelitt	israelitter	N;NDEF;PL
israelitt	israelitten	N;DEF;SG
dong	donger	N;NDEF;PL
dong	dongene	N;DEF;PL
dong	dongen	N;DEF;SG
bein	bein	N;NDEF;PL
bein	beina	N;DEF;PL
bein	beinet	N;DEF;SG
bein	beinene	N;DEF;PL
vinsje	vinsj	V;IMP
vinsje	vinsjer	V;PRS
vinsje	vinsjet	V;PST
restaurere	restaurer	V;IMP
restaurere	restaurerende	V.PTCP;PRS
restaurere	restaurert	V.PTCP;PST
restaurere	restaurerte	V;PST
restaurere	restaurerer	V;PRS
filosof	filosofen	N;DEF;SG
filosof	filosofene	N;DEF;PL
filosof	filosofer	N;NDEF;PL
mislykket	mislykkete	ADJ;DEF;SG+PL
mislykket	mislykket	ADJ;NEUT;SG
mislykket	mislykkede	ADJ;DEF;SG+PL
barnløs	barnløst	ADJ;NEUT;SG
barnløs	barnløse	ADJ;DEF;SG+PL
velkjent	velkjent	ADJ;NEUT;SG
velkjent	velkjente	ADJ;DEF;SG+PL
jukeboks	jukeboksen	N;DEF;SG
jukeboks	jukeboksene	N;DEF;PL
jukeboks	jukebokser	N;NDEF;PL
gås	gjæsene	N;DEF;PL
gås	gåsen	N;DEF;SG
gås	gjess	N;NDEF;PL
gås	gjessene	N;DEF;PL
gås	gjæser	N;NDEF;PL
gås	gåsa	N;DEF;SG
optimistisk	optimistiske	ADJ;DEF;SG+PL
optimistisk	optimistisk	ADJ;NEUT;SG
forsterker	forsterkerne	N;DEF;PL
forsterker	forsterkere	N;NDEF;PL
forsterker	forsterkeren	N;DEF;SG
tilhenger	tilhengere	N;NDEF;PL
tilhenger	tilhengerne	N;DEF;PL
tilhenger	tilhengeren	N;DEF;SG
notisbok	notisboka	N;DEF;SG
notisbok	notisbøkene	N;DEF;PL
notisbok	notisboken	N;DEF;SG
notisbok	notisbøker	N;NDEF;PL
hevelse	hevelser	N;NDEF;PL
hevelse	hevelsene	N;DEF;PL
hevelse	hevelsen	N;DEF;SG
bokholder	bokholderne	N;DEF;PL
bokholder	bokholdere	N;NDEF;PL
bokholder	bokholderen	N;DEF;SG
naturlig	naturlig	ADJ;NEUT;SG
naturlig	naturlige	ADJ;DEF;SG+PL
kaffer	kaffere	N;NDEF;PL
kaffer	kafferen	N;DEF;SG
kaffer	kafferne	N;DEF;PL
seycheller	seychellerne	N;DEF;PL
seycheller	seychellere	N;NDEF;PL
seycheller	seychelleren	N;DEF;SG
snill	snille	ADJ;DEF;SG+PL
snill	snilt	ADJ;NEUT;SG
baksete	baksetet	N;DEF;SG
baksete	bakseta	N;DEF;PL
baksete	bakseter	N;NDEF;PL
flyfrakt	flyfrakten	N;DEF;SG
sår	sår	N;NDEF;PL
sår	såre	ADJ;DEF;SG+PL
sår	sårene	N;DEF;PL
sår	sårt	ADJ;NEUT;SG
sår	såra	N;DEF;PL
sår	såret	N;DEF;SG
algerier	algerierne	N;DEF;PL
algerier	algeriere	N;NDEF;PL
algerier	algerieren	N;DEF;SG
universitet	universiteta	N;DEF;PL
universitet	universiteter	N;NDEF;PL
universitet	universitetet	N;DEF;SG
botaniker	botanikere	N;NDEF;PL
botaniker	botanikerne	N;DEF;PL
botaniker	botanikeren	N;DEF;SG
ting	tingene	N;DEF;PL
ting	ting	N;NDEF;PL
ting	tingen	N;DEF;SG
ting	tinget	N;DEF;SG
celle	cellen	N;DEF;SG
celle	cellene	N;DEF;PL
celle	celler	N;NDEF;PL
pukkel	pukler	N;NDEF;PL
pukkel	puklene	N;DEF;PL
pukkel	pukkelen	N;DEF;SG
trene	trena	V.PTCP;PST
trene	trente	V;PST
trene	tren	V;IMP
trene	trenende	V.PTCP;PRS
trene	trena	V;PST
trene	trenet	V;PST
trene	trener	V;PRS
trene	trent	V.PTCP;PST
basar	basaren	N;DEF;SG
basar	basarene	N;DEF;PL
basar	basarer	N;NDEF;PL
grunnflate	grunnflata	N;DEF;SG
grunnflate	grunnflatene	N;DEF;PL
grunnflate	grunnflater	N;NDEF;PL
rosin	rosinen	N;DEF;SG
rosin	rosinene	N;DEF;PL
rosin	rosina	N;DEF;SG
rosin	rosiner	N;NDEF;PL
spenning	spenninga	N;DEF;SG
spenning	spenninger	N;NDEF;PL
spenning	spenningene	N;DEF;PL
aksjonær	aksjonærer	N;NDEF;PL
aksjonær	aksjonæren	N;DEF;SG
aksjonær	aksjonærene	N;DEF;PL
kanadisk	kanadisk	ADJ;NEUT;SG
kanadisk	kanadiske	ADJ;DEF;SG+PL
økonom	økonomen	N;DEF;SG
økonom	økonomene	N;DEF;PL
økonom	økonomer	N;NDEF;PL
gjennombrudd	gjennombrudd	N;NDEF;PL
gjennombrudd	gjennombrudda	N;DEF;PL
gjennombrudd	gjennombruddet	N;DEF;SG
gjensidig	gjensidige	ADJ;DEF;SG+PL
gjensidig	gjensidig	ADJ;NEUT;SG
prestisje	prestisjen	N;DEF;SG
skisse	skissa	N;DEF;SG
skisse	skisser	N;NDEF;PL
skisse	skissene	N;DEF;PL
jakte	jaktende	V.PTCP;PRS
jakte	jakta	V;PST
jakte	jakter	V;PRS
jakte	jakt	V;IMP
jakte	jaktet	V;PST
hjerne	hjernen	N;DEF;SG
hjerne	hjerner	N;NDEF;PL
hjerne	hjernene	N;DEF;PL
bibliotekar	bibliotekarene	N;DEF;PL
bibliotekar	bibliotekarer	N;NDEF;PL
bibliotekar	bibliotekaren	N;DEF;SG
pisse	pissende	V.PTCP;PRS
pisse	pisset	V;PST
pisse	pist	V.PTCP;PST
pisse	pisser	V;PRS
pisse	piste	V;PST
pisse	piss	V;IMP
minutt	minuttet	N;DEF;SG
minutt	minutter	N;NDEF;PL
minutt	minutta	N;DEF;PL
minutt	minuttene	N;DEF;PL
offisiell	offisielt	ADJ;NEUT;SG
offisiell	offisielle	ADJ;DEF;SG+PL
uren	urene	ADJ;DEF;SG+PL
uren	urent	ADJ;NEUT;SG
regntid	regntida	N;DEF;SG
regntid	regntider	N;NDEF;PL
regntid	regntidene	N;DEF;PL
keiserinne	keiserinner	N;NDEF;PL
keiserinne	keiserinna	N;DEF;SG
keiserinne	keiserinnen	N;DEF;SG
keiserinne	keiserinnene	N;DEF;PL
unntak	unntakene	N;DEF;PL
unntak	unntaket	N;DEF;SG
unntak	unntaka	N;DEF;PL
unntak	unntak	N;NDEF;PL
datamaskin	datamaskinene	N;DEF;PL
datamaskin	datamaskinen	N;DEF;SG
datamaskin	datamaskiner	N;NDEF;PL
bøffel	bøflene	N;DEF;PL
bøffel	bøffelen	N;DEF;SG
bøffel	bøfler	N;NDEF;PL
trett	trettest	ADJ;SPRL;NDEF
trett	tretteste	ADJ;SPRL;DEF
trett	trettere	ADJ;CMPR
trett	trett	ADJ;NEUT;SG
trett	trette	ADJ;DEF;SG+PL
håndflate	håndflater	N;NDEF;PL
håndflate	håndflata	N;DEF;SG
håndflate	håndflatene	N;DEF;PL
bjørnebær	bjørnebæra	N;DEF;PL
bjørnebær	bjørnebæret	N;DEF;SG
bjørnebær	bjørnebær	N;NDEF;PL
scene	scenen	N;DEF;SG
scene	scener	N;NDEF;PL
scene	scenene	N;DEF;PL
løp	løpene	N;DEF;PL
løp	løpet	N;DEF;SG
løp	løp	N;NDEF;PL
løp	løpa	N;DEF;PL
fornyelse	fornyelsene	N;DEF;PL
fornyelse	fornyelsen	N;DEF;SG
fornyelse	fornyelser	N;NDEF;PL
ecuadorianer	ecuadorianerne	N;DEF;PL
ecuadorianer	ecuadorianeren	N;DEF;SG
ecuadorianer	ecuadorianere	N;NDEF;PL
oversjøisk	oversjøisk	ADJ;NEUT;SG
oversjøisk	oversjøiske	ADJ;DEF;SG+PL
betong	betongen	N;DEF;SG
rhodium	rhodiumet	N;DEF;SG
interessere	interesser	V;IMP
interessere	interessert	V.PTCP;PST
interessere	interesserer	V;PRS
interessere	interesserte	V;PST
uendret	uendrete	ADJ;DEF;SG+PL
uendret	uendret	ADJ;NEUT;SG
gnage	gnagde	V;PST
gnage	gnag	V;IMP
gnage	gnager	V;PRS
gnage	gnagd	V.PTCP;PST
gnage	gnaget	V;PST
gnage	gnaget	V.PTCP;PST
nasjonalsang	nasjonalsangene	N;DEF;PL
nasjonalsang	nasjonalsangen	N;DEF;SG
nasjonalsang	nasjonalsanger	N;NDEF;PL
publisitet	publisiteten	N;DEF;SG
bær	bæra	N;DEF;PL
bær	bæret	N;DEF;SG
bær	bær	N;NDEF;PL
svoger	svogere	N;NDEF;PL
svoger	svogerne	N;DEF;PL
svoger	svogeren	N;DEF;SG
lesepult	lesepulter	N;NDEF;PL
lesepult	lesepultene	N;DEF;PL
lesepult	lesepulten	N;DEF;SG
leite	lette	V;PST
leite	leit	V;IMP
leite	lett	V.PTCP;PST
leite	leiter	V;PRS
leite	leita	V;PST
bryte	brutt	V.PTCP;PST
bryte	brøyt	V;PST
bryte	brytende	V.PTCP;PRS
bryte	bryt	V;IMP
bryte	bryter	V;PRS
bryte	brøt	V;PST
orden	ordenen	N;DEF;SG
orden	ordenene	N;DEF;PL
orden	ordener	N;NDEF;PL
agenda	agendaen	N;DEF;SG
agenda	agendaer	N;NDEF;PL
agenda	agendaene	N;DEF;PL
frelser	frelsere	N;NDEF;PL
frelser	frelserne	N;DEF;PL
frelser	frelseren	N;DEF;SG
kontrollere	kontrollerer	V;PRS
kontrollere	kontrollert	V.PTCP;PST
kontrollere	kontrollerende	V.PTCP;PRS
kontrollere	kontrollerte	V;PST
kontrollere	kontroller	V;IMP
bred	bredeste	ADJ;SPRL;DEF
bred	bredt	ADJ;NEUT;SG
bred	brede	ADJ;DEF;SG+PL
bred	bredere	ADJ;CMPR
bred	bredest	ADJ;SPRL;NDEF
tape	tapen	N;DEF;SG
tape	taper	N;NDEF;PL
tape	tapene	N;DEF;PL
skoggrense	skoggrensa	N;DEF;SG
skoggrense	skoggrensene	N;DEF;PL
skoggrense	skoggrenser	N;NDEF;PL
skoggrense	skoggrensen	N;DEF;SG
ansvarlig	ansvarlig	ADJ;SPRL
ansvarlig	ansvarlig	ADJ;CMPR
ansvarlig	ansvarlige	ADJ;DEF;SG+PL
ansvarlig	ansvarlig	ADJ;NEUT;SG
identisk	identiske	ADJ;DEF;SG+PL
identisk	identisk	ADJ;NEUT;SG
ekkolodd	ekkolodda	N;DEF;PL
ekkolodd	ekkolodder	N;NDEF;PL
ekkolodd	ekkoloddet	N;DEF;SG
protein	proteinet	N;DEF;SG
protein	protein	N;NDEF;PL
protein	proteinene	N;DEF;PL
protein	proteina	N;DEF;PL
minimum	minimumet	N;DEF;SG
minimum	minimumer	N;NDEF;PL
minimum	minimaene	N;DEF;PL
minimum	minimumene	N;DEF;PL
partikkel	partiklene	N;DEF;PL
partikkel	partikler	N;NDEF;PL
partikkel	partikkelen	N;DEF;SG
turner	turneren	N;DEF;SG
turner	turnere	N;NDEF;PL
turner	turnerne	N;DEF;PL
dynamitt	dynamitten	N;DEF;SG
laken	lakenet	N;DEF;SG
laken	lakenene	N;DEF;PL
laken	laken	N;NDEF;PL
laken	lakena	N;DEF;PL
forventning	forventninga	N;DEF;SG
forventning	forventningene	N;DEF;PL
forventning	forventninger	N;NDEF;PL
forventning	forventningen	N;DEF;SG
kammer	kamre	N;NDEF;PL
kammer	kammeret	N;DEF;SG
kammer	kamrene	N;DEF;PL
nummen	numment	ADJ;NEUT
nummen	numne	ADJ;PL
nummen	nummenere	ADJ;CMPR
nummen	nummenest	ADJ;SPRL
dukke	dukkene	N;DEF;PL
dukke	dukka	N;DEF;SG
dukke	dukker	N;NDEF;PL
ur	uret	N;DEF;SG
ur	ur	N;NDEF;PL
ur	urene	N;DEF;PL
potensiell	potensielt	ADJ;NEUT;SG
potensiell	potensielle	ADJ;DEF;SG+PL
råmateriale	råmateriala	N;DEF;PL
råmateriale	råmaterialet	N;DEF;SG
råmateriale	råmaterialer	N;NDEF;PL
stasjonsvogn	stasjonsvognene	N;DEF;PL
stasjonsvogn	stasjonsvogner	N;NDEF;PL
stasjonsvogn	stasjonsvognen	N;DEF;SG
stasjonsvogn	stasjonsvogna	N;DEF;SG
tungtvann	tungtvannet	N;DEF;SG
fylke	fylker	N;NDEF;PL
fylke	fylket	N;DEF;SG
fylke	fylka	N;DEF;PL
monark	monarker	N;NDEF;PL
monark	monarken	N;DEF;SG
monark	monarkene	N;DEF;PL
laste	laster	V;PRS
laste	last	V;IMP
laste	lastende	V.PTCP;PRS
laste	lasta	V;PST
laste	lastet	V;PST
skolisse	skolissene	N;DEF;PL
skolisse	skolissa	N;DEF;SG
skolisse	skolisser	N;NDEF;PL
skolisse	skolissen	N;DEF;SG
ordfører	ordførere	N;NDEF;PL
ordfører	ordførerne	N;DEF;PL
ordfører	ordføreren	N;DEF;SG
wikipedianer	wikipedianerne	N;DEF;PL
wikipedianer	wikipedianeren	N;DEF;SG
wikipedianer	wikipedianere	N;NDEF;PL
femdoblet	femdoblete	ADJ;DEF;SG+PL
femdoblet	femdoblet	ADJ;NEUT;SG
alder	aldre	N;NDEF;PL
alder	aldrene	N;DEF;PL
alder	alderen	N;DEF;SG
alder	aldere	N;NDEF;PL
fryse	fryser	V;PRS
fryse	fryste	V;PST
fryse	frysende	V.PTCP;PRS
fryse	fryst	V.PTCP;PST
fryse	frys	V;IMP
fryse	fryse	V;IMP
mekanisk	mekanisk	ADJ;NEUT;SG
mekanisk	mekaniske	ADJ;DEF;SG+PL
sprade	spraden	N;DEF;SG
sprade	sprader	N;NDEF;PL
sprade	spradene	N;DEF;PL
åpen	åpent	ADJ;NEUT;SG
åpen	åpnere	ADJ;CMPR
åpen	åpnest	ADJ;SPRL;NDEF
åpen	åpneste	ADJ;SPRL;DEF
åpen	åpne	ADJ;DEF;SG+PL
medfødt	medfødte	ADJ;DEF;SG+PL
medfødt	medfødt	ADJ;NEUT;SG
felt	feltet	N;DEF;SG
felt	felt	N;NDEF;PL
felt	feltene	N;DEF;PL
felt	felta	N;DEF;PL
havbunn	havbunner	N;NDEF;PL
havbunn	havbunnene	N;DEF;PL
havbunn	havbunnen	N;DEF;SG
budbringer	budbringere	N;NDEF;PL
budbringer	budbringerne	N;DEF;PL
budbringer	budbringeren	N;DEF;SG
elev	eleven	N;DEF;SG
elev	elever	N;NDEF;PL
elev	elevene	N;DEF;PL
individ	individet	N;DEF;SG
individ	individa	N;DEF;PL
individ	individer	N;NDEF;PL
astat	astatet	N;DEF;SG
privatfly	privatflyet	N;DEF;SG
privatfly	privatflyene	N;DEF;PL
privatfly	privatfly	N;NDEF;PL
russer	russerne	N;DEF;PL
russer	russere	N;NDEF;PL
russer	russeren	N;DEF;SG
arkeologi	arkeologien	N;DEF;SG
nattpotte	nattpotten	N;DEF;SG
nattpotte	nattpottene	N;DEF;PL
nattpotte	nattpotter	N;NDEF;PL
gammelengelsk	gammelengelsken	N;DEF;SG
samleie	samleiet	N;DEF;SG
samleie	samleia	N;DEF;PL
samleie	samleier	N;NDEF;PL
samleie	samleiene	N;DEF;PL
armbåndsur	armbåndsur	N;NDEF;PL
armbåndsur	armbåndsuret	N;DEF;SG
armbåndsur	armbåndsura	N;DEF;PL
plutselig	plutselige	ADJ;DEF;SG+PL
plutselig	plutselig	ADJ;NEUT;SG
kaos	kaoset	N;DEF;SG
implantat	implantatet	N;DEF;SG
implantat	implantatene	N;DEF;PL
implantat	implantat	N;NDEF;PL
aseksuell	aseksuelt	ADJ;NEUT;SG
aseksuell	aseksuelle	ADJ;DEF;SG+PL
passivisering	passiviseringen	N;DEF;SG
passivisering	passiviseringer	N;NDEF;PL
passivisering	passiviseringene	N;DEF;PL
nabolag	nabolaga	N;DEF;PL
nabolag	nabolag	N;NDEF;PL
nabolag	nabolaget	N;DEF;SG
lufttett	lufttett	ADJ;NEUT;SG
lufttett	lufttette	ADJ;DEF;SG+PL
syre	syren	N;DEF;SG
syre	syrer	N;NDEF;PL
syre	syrene	N;DEF;PL
avsporing	avsporingen	N;DEF;SG
avsporing	avsporingene	N;DEF;PL
avsporing	avsporinger	N;NDEF;PL
svak	svakest	ADJ;SPRL;NDEF
svak	svake	ADJ;DEF;SG+PL
svak	svakere	ADJ;CMPR
svak	svakeste	ADJ;SPRL;DEF
svak	svakt	ADJ;NEUT;SG
kolombianer	kolombianere	N;NDEF;PL
kolombianer	kolombianerne	N;DEF;PL
kolombianer	kolombianeren	N;DEF;SG
kreft	kreften	N;DEF;SG
xenon	xenonet	N;DEF;SG
myndighet	myndigheten	N;DEF;SG
myndighet	myndigheter	N;NDEF;PL
myndighet	myndighetene	N;DEF;PL
myndighet	myndigheta	N;DEF;SG
plankton	planktonet	N;DEF;SG
hete	hett	V.PTCP;PST
hete	heten	N;DEF;SG
hete	hetende	V.PTCP;PRS
hete	heter	V;PRS
hete	heta	V;PST
hete	hetet	V;PST
fløy	fløyene	N;DEF;PL
fløy	fløyen	N;DEF;SG
fløy	fløyer	N;NDEF;PL
fløy	fløya	N;DEF;SG
slekt	slekta	N;DEF;SG
slekt	slektene	N;DEF;PL
slekt	slekter	N;NDEF;PL
slekt	slekten	N;DEF;SG
svinelær	svinelæret	N;DEF;SG
mat	maten	N;DEF;SG
vernehjelm	vernehjelmen	N;DEF;SG
vernehjelm	vernehjelmer	N;NDEF;PL
vernehjelm	vernehjelmene	N;DEF;PL
mistenksom	mistenksomme	ADJ;DEF;SG+PL
mistenksom	mistenksomt	ADJ;NEUT;SG
nettkamera	nettkameraet	N;DEF;SG
nettkamera	nettkamera	N;NDEF;PL
nettkamera	nettkameraene	N;DEF;PL
knapphullsblomst	knapphullsblomstene	N;DEF;PL
knapphullsblomst	knapphullsblomsten	N;DEF;SG
knapphullsblomst	knapphullsblomster	N;NDEF;PL
bratsj	bratsjer	N;NDEF;PL
bratsj	bratsjene	N;DEF;PL
bratsj	bratsjen	N;DEF;SG
piggsvin	piggsvinet	N;DEF;SG
piggsvin	piggsvina	N;DEF;PL
piggsvin	piggsvin	N;NDEF;PL
hånd	hender	N;NDEF;PL
hånd	hånda	N;DEF;SG
hånd	hendene	N;DEF;PL
hånd	hånden	N;DEF;SG
frysepunkt	frysepunkt	N;NDEF;PL
frysepunkt	frysepunktet	N;DEF;SG
frysepunkt	frysepunkta	N;DEF;PL
frysepunkt	frysepunktene	N;DEF;PL
aksel	akselen	N;DEF;SG
aksel	akslene	N;DEF;PL
aksel	aksler	N;NDEF;PL
håndkle	håndkleet	N;DEF;SG
håndkle	håndklærne	N;DEF;PL
håndkle	håndklær	N;NDEF;PL
kondensasjon	kondensasjonen	N;DEF;SG
kondensasjon	kondensasjonene	N;DEF;PL
kondensasjon	kondensasjoner	N;NDEF;PL
måke	måkene	N;DEF;PL
måke	måkende	V.PTCP;PRS
måke	måkte	V;PST
måke	måk	V;IMP
måke	måker	N;NDEF;PL
måke	måken	N;DEF;SG
måke	måker	V;PRS
måke	måka	V.PTCP;PST
måke	måka	N;DEF;SG
måke	måkt	V.PTCP;PST
måke	måket	V.PTCP;PST
juveler	juveleren	N;DEF;SG
juveler	juvelerene	N;DEF;PL
juveler	juvelerer	N;NDEF;PL
hval	hvalen	N;DEF;SG
hval	hvaler	N;NDEF;PL
hval	hvalene	N;DEF;PL
barrikade	barrikaden	N;DEF;SG
barrikade	barrikader	N;NDEF;PL
barrikade	barrikadene	N;DEF;PL
jernbanestasjon	jernbanestasjonene	N;DEF;PL
jernbanestasjon	jernbanestasjoner	N;NDEF;PL
jernbanestasjon	jernbanestasjonen	N;DEF;SG
vietnameser	vietnameseren	N;DEF;SG
vietnameser	vietnamesere	N;NDEF;PL
vietnameser	vietnameserne	N;DEF;PL
sørende	sørenden	N;DEF;SG
håndtering	håndteringer	N;NDEF;PL
håndtering	håndteringen	N;DEF;SG
håndtering	håndteringene	N;DEF;PL
flamsk	flamske	ADJ;DEF;SG+PL
flamsk	flamsk	ADJ;NEUT;SG
kyrillisk	kyrillisk	ADJ;NEUT;SG
kyrillisk	kyrilliske	ADJ;DEF;SG+PL
berømthet	berømtheta	N;DEF;SG
berømthet	berømthetene	N;DEF;PL
berømthet	berømtheter	N;NDEF;PL
rop	ropet	N;DEF;SG
rop	ropa	N;DEF;PL
rop	rop	N;NDEF;PL
motorvei	motorveiene	N;DEF;PL
motorvei	motorveier	N;NDEF;PL
motorvei	motorveien	N;DEF;SG
passform	passformen	N;DEF;SG
passform	passformer	N;NDEF;PL
passform	passforma	N;DEF;SG
passform	passformene	N;DEF;PL
manuskript	manuskripta	N;DEF;PL
manuskript	manuskriptet	N;DEF;SG
manuskript	manuskriptene	N;DEF;PL
manuskript	manuskript	N;NDEF;PL
manuskript	manuskripter	N;NDEF;PL
lidelse	lidelsene	N;DEF;PL
lidelse	lidelsen	N;DEF;SG
lidelse	lidelser	N;NDEF;PL
spille	spilte	V;PST
spille	spiller	V;PRS
spille	spillende	V.PTCP;PRS
spille	spill	V;IMP
spille	spilt	V.PTCP;PST
mygg	myggene	N;DEF;PL
mygg	myggen	N;DEF;SG
mygg	mygg	N;NDEF;PL
gen	gen	N;NDEF;PL
gen	genene	N;DEF;PL
gen	genen	N;DEF;SG
gen	gena	N;DEF;PL
gen	genet	N;DEF;SG
forvente	forventet	V;PST
forvente	forvent	V;IMP
forvente	forventer	V;PRS
synder	synderen	N;DEF;SG
synder	synderne	N;DEF;PL
synder	syndere	N;NDEF;PL
strømavtaker	strømavtakere	N;NDEF;PL
strømavtaker	strømavtakeren	N;DEF;SG
strømavtaker	strømavtakerne	N;DEF;PL
mannlig	mannlige	ADJ;DEF;SG+PL
mannlig	mannlig	ADJ;NEUT;SG
prisliste	prislista	N;DEF;SG
prisliste	prislistene	N;DEF;PL
prisliste	prislister	N;NDEF;PL
pels	pelsene	N;DEF;PL
pels	pelsen	N;DEF;SG
pels	pelser	N;NDEF;PL
selvportrett	selvportretta	N;DEF;PL
selvportrett	selvportrett	N;NDEF;PL
selvportrett	selvportrettet	N;DEF;SG
selvportrett	selvportretter	N;NDEF;PL
selvportrett	selvportrettene	N;DEF;PL
grave	gravende	V.PTCP;PRS
grave	gravde	V;PST
grave	gravd	V.PTCP;PST
grave	grav	V;IMP
grave	graver	V;PRS
skuespillerinne	skuespillerinner	N;NDEF;PL
skuespillerinne	skuespillerinna	N;DEF;SG
skuespillerinne	skuespillerinnene	N;DEF;PL
eddiksyre	eddiksyren	N;DEF;SG
eddiksyre	eddiksyra	N;DEF;SG
starte	startet	V;PST
starte	start	V;IMP
starte	starter	V;PRS
italiener	italieneren	N;DEF;SG
italiener	italienerne	N;DEF;PL
italiener	italienere	N;NDEF;PL
håndveske	håndveska	N;DEF;SG
håndveske	håndvesker	N;NDEF;PL
håndveske	håndveskene	N;DEF;PL
overflate	overflatene	N;DEF;PL
overflate	overflater	N;NDEF;PL
overflate	overflaten	N;DEF;SG
vinterlig	vinterlige	ADJ;DEF;SG+PL
vinterlig	vinterlig	ADJ;NEUT;SG
infisere	infiser	V;IMP
infisere	infiserte	V;PST
infisere	infisert	V.PTCP;PST
infisere	infiserende	V.PTCP;PRS
infisere	infiserer	V;PRS
iraker	irakerne	N;DEF;PL
iraker	irakeren	N;DEF;SG
iraker	irakere	N;NDEF;PL
felle	feller	N;NDEF;PL
felle	fellen	N;DEF;SG
felle	felt	V.PTCP;PST
felle	fell	V;IMP
felle	feller	V;PRS
felle	fellene	N;DEF;PL
felle	felte	V;PST
bøk	bøker	N;NDEF;PL
bøk	bøkene	N;DEF;PL
bøk	bøken	N;DEF;SG
mørkbrun	mørkbrunt	ADJ;NEUT;SG
mørkbrun	mørkbrune	ADJ;DEF;SG+PL
protestantisk	protestantiske	ADJ;DEF;SG+PL
protestantisk	protestantisk	ADJ;NEUT;SG
sete	setene	N;DEF;PL
sete	setet	N;DEF;SG
sete	seter	N;NDEF;PL
sete	seta	N;DEF;PL
stadion	stadionet	N;DEF;SG
stadion	stadion	N;NDEF;PL
stadion	stadiona	N;DEF;PL
pulver	pulvere	N;NDEF;PL
pulver	pulvera	N;DEF;PL
pulver	pulveret	N;DEF;SG
svigersøster	svigersøstrene	N;DEF;PL
svigersøster	svigersøsteren	N;DEF;SG
svigersøster	svigersøstrer	N;NDEF;PL
svigersøster	svigersøstre	N;NDEF;PL
indikere	indiker	V;IMP
indikere	indikerende	V.PTCP;PRS
indikere	indikerte	V;PST
indikere	indikerer	V;PRS
indikere	indikert	V.PTCP;PST
syklus	syklusene	N;DEF;PL
syklus	syklusen	N;DEF;SG
syklus	sykluser	N;NDEF;PL
turkmener	turkmenerne	N;DEF;PL
turkmener	turkmeneren	N;DEF;SG
turkmener	turkmenere	N;NDEF;PL
bussjåfør	bussjåførene	N;DEF;PL
bussjåfør	bussjåføren	N;DEF;SG
bussjåfør	bussjåfører	N;NDEF;PL
homoseksualitet	homoseksualiteten	N;DEF;SG
byråkratisk	byråkratisk	ADJ;NEUT;SG
byråkratisk	byråkratiske	ADJ;DEF;SG+PL
mengde	mengden	N;DEF;SG
mengde	mengder	N;NDEF;PL
mengde	mengdene	N;DEF;PL
kunstverk	kunstverker	N;NDEF;PL
kunstverk	kunstverka	N;DEF;PL
kunstverk	kunstverket	N;DEF;SG
akseptere	aksepterer	V;PRS
akseptere	aksepterende	V.PTCP;PRS
akseptere	akseptert	V.PTCP;PST
akseptere	aksepterte	V;PST
akseptere	aksepter	V;IMP
hankjønn	hankjønna	N;DEF;PL
hankjønn	hankjønn	N;NDEF;PL
hankjønn	hankjønnene	N;DEF;PL
hankjønn	hankjønnet	N;DEF;SG
industrialisere	industrialiser	V;IMP
industrialisere	industrialiserende	V.PTCP;PRS
industrialisere	industrialiserer	V;PRS
industrialisere	industrialisert	V.PTCP;PST
industrialisere	industrialiserte	V;PST
multiplikasjon	multiplikasjonen	N;DEF;SG
multiplikasjon	multiplikasjonene	N;DEF;PL
multiplikasjon	multiplikasjoner	N;NDEF;PL
jord	jorda	N;DEF;SG
undertøy	undertøyet	N;DEF;SG
flystripe	flystripa	N;DEF;SG
flystripe	flystripene	N;DEF;PL
flystripe	flystriper	N;NDEF;PL
varsler	varslerne	N;DEF;PL
varsler	varsleren	N;DEF;SG
varsler	varslere	N;NDEF;PL
fiende	fiender	N;NDEF;PL
fiende	fienden	N;DEF;SG
fiende	fiendene	N;DEF;PL
afar	afarene	N;DEF;PL
afar	afarer	N;NDEF;PL
afar	afaren	N;DEF;SG
naturgass	naturgassene	N;DEF;PL
naturgass	naturgasser	N;NDEF;PL
naturgass	naturgassen	N;DEF;SG
utforming	utforminger	N;NDEF;PL
utforming	utforminga	N;DEF;SG
utforming	utformingene	N;DEF;PL
utforming	utformingen	N;DEF;SG
turist	turisten	N;DEF;SG
turist	turistene	N;DEF;PL
turist	turister	N;NDEF;PL
apekatt	apekatten	N;DEF;SG
apekatt	apekatter	N;NDEF;PL
apekatt	apekattene	N;DEF;PL
utnytte	utnytter	V;PRS
utnytte	utnytta	V;PST
utnytte	utnytt	V;IMP
utnytte	utnyttet	V;PST
sutra	sutraen	N;DEF;SG
sutra	sutraer	N;NDEF;PL
sutra	sutraene	N;DEF;PL
kappe	kappen	N;DEF;SG
kappe	kappene	N;DEF;PL
kappe	kapper	N;NDEF;PL
spir	spiren	N;DEF;SG
spir	spirer	N;NDEF;PL
spir	spirene	N;DEF;PL
ghanesisk	ghanesiske	ADJ;DEF;SG+PL
ghanesisk	ghanesisk	ADJ;NEUT;SG
boksåpner	boksåpnerne	N;DEF;PL
boksåpner	boksåpneren	N;DEF;SG
boksåpner	boksåpnere	N;NDEF;PL
leiebil	leiebilene	N;DEF;PL
leiebil	leiebiler	N;NDEF;PL
leiebil	leiebilen	N;DEF;SG
makrell	makrellene	N;DEF;PL
makrell	makrellen	N;DEF;SG
makrell	makreller	N;NDEF;PL
tørketrommel	tørketromlene	N;DEF;PL
tørketrommel	tørketromler	N;NDEF;PL
tørketrommel	tørketrommelen	N;DEF;SG
lingvistikk	lingvistikken	N;DEF;SG
geit	geita	N;DEF;SG
geit	geiter	N;NDEF;PL
geit	geitene	N;DEF;PL
sentrifugal	sentrifugale	ADJ;DEF;SG+PL
sentrifugal	sentrifugalt	ADJ;NEUT;SG
tunnelbane	tunnelbanen	N;DEF;SG
tunnelbane	tunnelbanene	N;DEF;PL
tunnelbane	tunnelbaner	N;NDEF;PL
område	områdene	N;DEF;PL
område	området	N;DEF;SG
område	områder	N;NDEF;PL
område	områda	N;DEF;PL
lekeplass	lekeplasser	N;NDEF;PL
lekeplass	lekeplassene	N;DEF;PL
lekeplass	lekeplassen	N;DEF;SG
adgang	adgangen	N;DEF;SG
adgang	adganger	N;NDEF;PL
adgang	adgangene	N;DEF;PL
trakassere	trakasser	V;IMP
trakassere	trakasserte	V;PST
trakassere	trakasserer	V;PRS
trakassere	trakassert	V.PTCP;PST
trakassere	trakasserende	V.PTCP;PRS
statlig	statlige	ADJ;DEF;SG+PL
statlig	statlig	ADJ;NEUT;SG
kirke	kirken	N;DEF;SG
kirke	kirkene	N;DEF;PL
kirke	kirker	N;NDEF;PL
kirke	kirka	N;DEF;SG
motta	motta	V;IMP
motta	mottakende	V.PTCP;PRS
motta	mottok	V;PST
motta	mottar	V;PRS
motta	mottatt	V.PTCP;PST
hore	horer	N;NDEF;PL
hore	horene	N;DEF;PL
hore	hora	N;DEF;SG
høns	hønsa	N;DEF;PL
høns	hønsene	N;DEF;PL
akkar	akkarer	N;NDEF;PL
akkar	akkaren	N;DEF;SG
akkar	akkarene	N;DEF;PL
endestasjon	endestasjonene	N;DEF;PL
endestasjon	endestasjoner	N;NDEF;PL
endestasjon	endestasjonen	N;DEF;SG
tannverk	tannverken	N;DEF;SG
andreplass	andreplassen	N;DEF;SG
andreplass	andreplasser	N;NDEF;PL
andreplass	andreplassene	N;DEF;PL
triumfere	triumferer	V;PRS
triumfere	triumfert	V.PTCP;PST
triumfere	triumferte	V;PST
triumfere	triumfer	V;IMP
legendarisk	legendarisk	ADJ;NEUT;SG
legendarisk	legendariske	ADJ;DEF;SG+PL
universell	universelt	ADJ;NEUT;SG
universell	universelle	ADJ;DEF;SG+PL
angolaner	angolaneren	N;DEF;SG
angolaner	angolanerne	N;DEF;PL
angolaner	angolanere	N;NDEF;PL
assistere	assistert	V.PTCP;PST
assistere	assisterer	V;PRS
assistere	assister	V;IMP
assistere	assisterende	V.PTCP;PRS
assistere	assisterte	V;PST
permanent	permanente	ADJ;DEF;SG+PL
permanent	permanent	ADJ;NEUT;SG
grossist	grossistene	N;DEF;PL
grossist	grossisten	N;DEF;SG
grossist	grossister	N;NDEF;PL
øye	øynene	N;DEF;PL
øye	øyne	N;NDEF;PL
øye	øyer	N;NDEF;PL
øye	øyet	N;DEF;SG
alkohol	alkoholer	N;NDEF;PL
alkohol	alkoholen	N;DEF;SG
alkohol	alkoholene	N;DEF;PL
argentiner	argentinerne	N;DEF;PL
argentiner	argentineren	N;DEF;SG
argentiner	argentinere	N;NDEF;PL
platina	platinaet	N;DEF;SG
humoristisk	humoristisk	ADJ;NEUT;SG
humoristisk	humoristiske	ADJ;DEF;SG+PL
tips	tipsa	N;DEF;PL
tips	tips	N;NDEF;PL
tips	tipsene	N;DEF;PL
tips	tipset	N;DEF;SG
solbrille	solbrillene	N;DEF;PL
solbrille	solbriller	N;NDEF;PL
solbrille	solbrilla	N;DEF;SG
vibrasjon	vibrasjoner	N;NDEF;PL
vibrasjon	vibrasjonene	N;DEF;PL
vibrasjon	vibrasjonen	N;DEF;SG
dreie	dreia	V;PST
dreie	drei	V;IMP
dreie	dreiende	V.PTCP;PRS
dreie	dreid	V.PTCP;PST
dreie	dreier	V;PRS
dreie	dreiet	V.PTCP;PST
dreie	dreide	V;PST
keramisk	keramiske	ADJ;DEF;SG+PL
keramisk	keramisk	ADJ;NEUT;SG
ingeniør	ingeniøren	N;DEF;SG
ingeniør	ingeniørene	N;DEF;PL
ingeniør	ingeniører	N;NDEF;PL
aserbajdsjansk	aserbajdsjansken	N;DEF;SG
aserbajdsjansk	aserbajdsjansk	ADJ;NEUT;SG
aserbajdsjansk	aserbajdsjanske	ADJ;DEF;SG+PL
diakon	diakonen	N;DEF;SG
diakon	diakonene	N;DEF;PL
diakon	diakoner	N;NDEF;PL
myke	myka	V.PTCP;PST
myke	myk	V;IMP
myke	myket	V.PTCP;PST
myke	myka	V;PST
myke	mykende	V.PTCP;PRS
myke	mykte	V;PST
myke	myker	V;PRS
gelatin	gelatinen	N;DEF;SG
føde	fødte	V;PST
føde	født	V.PTCP;PST
føde	føder	V;PRS
føde	fød	V;IMP
koloni	kolonier	N;NDEF;PL
koloni	koloniene	N;DEF;PL
koloni	kolonien	N;DEF;SG
fantastisk	fantastisk	ADJ;NEUT;SG
fantastisk	fantastiske	ADJ;DEF;SG+PL
abakus	abakusen	N;DEF;SG
abakus	abakuser	N;NDEF;PL
abakus	abakusene	N;DEF;PL
turnering	turneringa	N;DEF;SG
turnering	turneringer	N;NDEF;PL
turnering	turneringene	N;DEF;PL
gjel	gjela	N;DEF;PL
gjel	gjelene	N;DEF;PL
gjel	gjelet	N;DEF;SG
gjel	gjel	N;NDEF;PL
usikkerhet	usikkerheten	N;DEF;SG
usikkerhet	usikkerhetene	N;DEF;PL
usikkerhet	usikkerheter	N;NDEF;PL
fortelle	fortalte	V;PST
fortelle	fortalt	V.PTCP;PST
fortelle	fortellende	V.PTCP;PRS
fortelle	fortell	V;IMP
fortelle	forteller	V;PRS
struts	strutsene	N;DEF;PL
struts	strutsen	N;DEF;SG
struts	strutser	N;NDEF;PL
mykne	myknet	V;PST
mykne	mykner	V;PRS
mykne	myknende	V.PTCP;PRS
mykne	mykna	V;PST
revolusjonere	revolusjonerte	V;PST
revolusjonere	revolusjonert	V.PTCP;PST
revolusjonere	revolusjonerer	V;PRS
revolusjonere	revolusjoner	V;IMP
comeback	comebacka	N;DEF;PL
comeback	comeback	N;NDEF;PL
comeback	comebacken	N;DEF;SG
lengsel	lengsler	N;NDEF;PL
lengsel	lengselen	N;DEF;SG
lengsel	lengslene	N;DEF;PL
dinosaur	dinosaurene	N;DEF;PL
dinosaur	dinosaurer	N;NDEF;PL
dinosaur	dinosauren	N;DEF;SG
tømmerstokk	tømmerstokker	N;NDEF;PL
tømmerstokk	tømmerstokkene	N;DEF;PL
tømmerstokk	tømmerstokken	N;DEF;SG
kaptein	kapteiner	N;NDEF;PL
kaptein	kapteinen	N;DEF;SG
kaptein	kapteinene	N;DEF;PL
jerv	jervene	N;DEF;PL
jerv	jerven	N;DEF;SG
jerv	jerver	N;NDEF;PL
komponent	komponentene	N;DEF;PL
komponent	komponenter	N;NDEF;PL
komponent	komponenten	N;DEF;SG
bestyrer	bestyrere	N;NDEF;PL
bestyrer	bestyrerne	N;DEF;PL
bestyrer	bestyreren	N;DEF;SG
sikring	sikringer	N;NDEF;PL
sikring	sikringen	N;DEF;SG
sikring	sikringene	N;DEF;PL
eksistere	eksister	V;IMP
eksistere	eksisterende	V.PTCP;PRS
eksistere	eksistert	V.PTCP;PST
eksistere	eksisterte	V;PST
eksistere	eksisterer	V;PRS
adverb	adverbet	N;DEF;SG
adverb	adverber	N;NDEF;PL
adverb	adverbene	N;DEF;PL
adverb	adverb	N;NDEF;PL
retorikk	retorikken	N;DEF;SG
forfriske	forfriskende	V.PTCP;PRS
forfriske	forfrisker	V;PRS
forfriske	forfriska	V;PST
forfriske	forfrisk	V;IMP
putetrekk	putetrekka	N;DEF;PL
putetrekk	putetrekket	N;DEF;SG
putetrekk	putetrekk	N;NDEF;PL
vakker	vakrest	ADJ;SPRL;NDEF
vakker	vakreste	ADJ;SPRL;DEF
vakker	vakkert	ADJ;NEUT;SG
vakker	vakre	ADJ;DEF;SG+PL
vakker	vakrere	ADJ;CMPR
forbruker	forbrukere	N;NDEF;PL
forbruker	forbrukerne	N;DEF;PL
forbruker	forbrukeren	N;DEF;SG
kjedereaksjon	kjedereaksjoner	N;NDEF;PL
kjedereaksjon	kjedereaksjonene	N;DEF;PL
kjedereaksjon	kjedereaksjonen	N;DEF;SG
purre	purren	N;DEF;SG
purre	purrene	N;DEF;PL
purre	purrer	N;NDEF;PL
pessimisme	pessimismen	N;DEF;SG
turnpike	turnpiken	N;DEF;SG
turnpike	turnpiker	N;NDEF;PL
turnpike	turnpikene	N;DEF;PL
spindelvev	spindelvevene	N;DEF;PL
spindelvev	spindelvever	N;NDEF;PL
spindelvev	spindelvevet	N;DEF;SG
spindelvev	spindelvev	N;NDEF;PL
spindelvev	spindelveva	N;DEF;PL
spindelvev	spindelveven	N;DEF;SG
tygge	tygg	V;IMP
tygge	tygget	V.PTCP;PST
tygge	tygger	V;PRS
tygge	tygde	V;PST
tygge	tyggende	V.PTCP;PRS
tygge	tygget	V;PST
nordisk	nordisk	ADJ;NEUT;SG
nordisk	nordiske	ADJ;DEF;SG+PL
gammeldags	gammeldagse	ADJ;DEF;SG+PL
gammeldags	gammeldags	ADJ;NEUT;SG
subtrahere	subtrahert	V.PTCP;PST
subtrahere	subtraher	V;IMP
subtrahere	subtraherer	V;PRS
subtrahere	subtraherte	V;PST
subtrahere	subtraherende	V.PTCP;PRS
anakronisme	anakronismen	N;DEF;SG
anakronisme	anakronismer	N;NDEF;PL
anakronisme	anakronismene	N;DEF;PL
varsle	varsler	V;PRS
varsle	varslende	V.PTCP;PRS
varsle	varsle	V;IMP
varsle	varslet	V;PST
askebeger	askebegrene	N;DEF;PL
askebeger	askebegre	N;NDEF;PL
askebeger	askebegeret	N;DEF;SG
skrog	skroget	N;DEF;SG
skrog	skrog	N;NDEF;PL
skrog	skroga	N;DEF;PL
legemiddel	legemiddelet	N;DEF;SG
legemiddel	legemidlene	N;DEF;PL
legemiddel	legemidler	N;NDEF;PL
legemiddel	legemidla	N;DEF;PL
fastnøkkel	fastnøklene	N;DEF;PL
fastnøkkel	fastnøkler	N;NDEF;PL
fastnøkkel	fastnøkkelen	N;DEF;SG
topp	toppene	N;DEF;PL
topp	topper	N;NDEF;PL
topp	toppen	N;DEF;SG
etanol	etanolen	N;DEF;SG
glassverk	glassverkene	N;DEF;PL
glassverk	glassverker	N;NDEF;PL
glassverk	glassverket	N;DEF;SG
transportere	transporterer	V;PRS
transportere	transporter	V;IMP
transportere	transportert	V.PTCP;PST
transportere	transporterte	V;PST
ressurs	ressursen	N;DEF;SG
ressurs	ressurser	N;NDEF;PL
ressurs	ressursene	N;DEF;PL
konsulent	konsulentene	N;DEF;PL
konsulent	konsulenter	N;NDEF;PL
konsulent	konsulenten	N;DEF;SG
høl	hølene	N;DEF;PL
høl	hølen	N;DEF;SG
høl	høler	N;NDEF;PL
influensa	influensaen	N;DEF;SG
influensa	influensaene	N;DEF;PL
influensa	influensaer	N;NDEF;PL
knapp	knappen	N;DEF;SG
knapp	knappene	N;DEF;PL
knapp	knapper	N;NDEF;PL
morse	morsa	V;PST
morse	morsen	N;DEF;SG
morse	morser	V;PRS
morse	morset	V;PST
morse	mors	V;IMP
kalkun	kalkuner	N;NDEF;PL
kalkun	kalkunen	N;DEF;SG
kalkun	kalkunene	N;DEF;PL
jekk	jekkene	N;DEF;PL
jekk	jekker	N;NDEF;PL
jekk	jekken	N;DEF;SG
forslag	forslag	N;NDEF;PL
forslag	forslaga	N;DEF;PL
forslag	forslaget	N;DEF;SG
forslag	forslagene	N;DEF;PL
åndedrag	åndedragene	N;DEF;PL
åndedrag	åndedrag	N;NDEF;PL
åndedrag	åndedraget	N;DEF;SG
synge	syngende	V.PTCP;PRS
synge	sunget	V.PTCP;PST
synge	synger	V;PRS
synge	sang	V;PST
synge	syng	V;IMP
brannmur	brannmurer	N;NDEF;PL
brannmur	brannmurene	N;DEF;PL
brannmur	brannmuren	N;DEF;SG
undulat	undulater	N;NDEF;PL
undulat	undulaten	N;DEF;SG
undulat	undulatene	N;DEF;PL
prinsipiell	prinsipielle	ADJ;DEF;SG+PL
prinsipiell	prinsipielt	ADJ;NEUT;SG
nådeløs	nådeløst	ADJ;NEUT;SG
nådeløs	nådeløse	ADJ;DEF;SG+PL
rullebane	rullebaner	N;NDEF;PL
rullebane	rullebanen	N;DEF;SG
rullebane	rullebanene	N;DEF;PL
forgifte	forgifter	V;PRS
forgifte	forgift	V;IMP
forgifte	forgiftet	V;PST
lengde	lengder	N;NDEF;PL
lengde	lengden	N;DEF;SG
lengde	lengdene	N;DEF;PL
svindel	svindelen	N;DEF;SG
svindel	svindler	N;NDEF;PL
svindel	svindlene	N;DEF;PL
kobberrør	kobberrørene	N;DEF;PL
kobberrør	kobberrøret	N;DEF;SG
kobberrør	kobberrøra	N;DEF;PL
kobberrør	kobberrør	N;NDEF;PL
stråling	strålinger	N;NDEF;PL
stråling	strålinga	N;DEF;SG
stråling	strålingene	N;DEF;PL
stråling	strålingen	N;DEF;SG
kafé	kaféene	N;DEF;PL
kafé	kaféer	N;NDEF;PL
kafé	kaféen	N;DEF;SG
kafé	kafeen	N;DEF;SG
kniv	kniven	N;DEF;SG
kniv	knivene	N;DEF;PL
kniv	kniver	N;NDEF;PL
regn	regnet	N;DEF;SG
tiende	tiender	N;NDEF;PL
tiende	tiendene	N;DEF;PL
tiende	tienden	N;DEF;SG
splitt	splitten	N;DEF;SG
splitt	splittene	N;DEF;PL
splitt	splitter	N;NDEF;PL
eplepai	eplepaier	N;NDEF;PL
eplepai	eplepaien	N;DEF;SG
eplepai	eplepaiene	N;DEF;PL
havn	havna	N;DEF;SG
havn	havnene	N;DEF;PL
havn	havnen	N;DEF;SG
havn	havner	N;NDEF;PL
befrukte	befruktende	V.PTCP;PRS
befrukte	befrukter	V;PRS
befrukte	befrukta	V;PST
befrukte	befrukt	V;IMP
befrukte	befruktet	V;PST
sentralstasjon	sentralstasjonen	N;DEF;SG
sentralstasjon	sentralstasjoner	N;NDEF;PL
sentralstasjon	sentralstasjonene	N;DEF;PL
esperanto	esperantoen	N;DEF;SG
smertefull	smertefulle	ADJ;DEF;SG+PL
smertefull	smertefullt	ADJ;NEUT;SG
innhøste	innhøst	V;IMP
innhøste	innhøstet	V;PST
innhøste	innhøster	V;PRS
bokser	bokserne	N;DEF;PL
bokser	bokseren	N;DEF;SG
bokser	boksere	N;NDEF;PL
forbudt	forbudt	ADJ;NEUT;SG
forbudt	forbudte	ADJ;DEF;SG+PL
superlativ	superlativer	N;NDEF;PL
superlativ	superlativen	N;DEF;SG
superlativ	superlativene	N;DEF;PL
sonde	sondene	N;DEF;PL
sonde	sonden	N;DEF;SG
sonde	sonder	N;NDEF;PL
russisk	russiske	ADJ;DEF;SG+PL
russisk	russisken	N;DEF;SG
russisk	russisk	ADJ;NDEF;NEUT;SG
propan	propanen	N;DEF;SG
tryllekunstner	tryllekunstneren	N;DEF;SG
tryllekunstner	tryllekunstnerne	N;DEF;PL
tryllekunstner	tryllekunstnere	N;NDEF;PL
tillatelse	tillatelsen	N;DEF;SG
tillatelse	tillatelsene	N;DEF;PL
tillatelse	tillatelser	N;NDEF;PL
løpe	løp	V;IMP
løpe	løpt	V.PTCP;PST
løpe	løp	V;PST
løpe	løpende	V.PTCP;PRS
løpe	løper	V;PRS
tøs	tøsene	N;DEF;PL
tøs	tøsen	N;DEF;SG
tøs	tøser	N;NDEF;PL
tøs	tøsa	N;DEF;SG
diplomatisk	diplomatiske	ADJ;DEF;SG+PL
diplomatisk	diplomatisk	ADJ;NEUT;SG
informasjon	informasjoner	N;NDEF;PL
informasjon	informasjonen	N;DEF;SG
informasjon	informasjonene	N;DEF;PL
oppfinnelse	oppfinnelser	N;NDEF;PL
oppfinnelse	oppfinnelsene	N;DEF;PL
oppfinnelse	oppfinnelsen	N;DEF;SG
våt	våtere	ADJ;CMPR
våt	våte	ADJ;DEF;SG+PL
våt	våteste	ADJ;SPRL;DEF
våt	vått	ADJ;NEUT;SG
våt	våtest	ADJ;SPRL;NDEF
torsk	torsken	N;DEF;SG
torsk	torsker	N;NDEF;PL
torsk	torskene	N;DEF;PL
determinativ	determinativ	N;NDEF;PL
determinativ	determinativene	N;DEF;PL
determinativ	determinativet	N;DEF;SG
determinativ	determinativa	N;DEF;PL
determinativ	determinativer	N;NDEF;PL
albino	albinoene	N;DEF;PL
albino	albinoer	N;NDEF;PL
albino	albinoen	N;DEF;SG
hoppe	hopper	V;PRS
hoppe	hoppa	V;PST
hoppe	hoppa	N;DEF;SG
hoppe	hoppene	N;DEF;PL
hoppe	hoppende	V.PTCP;PRS
hoppe	hopper	N;NDEF;PL
hoppe	hopp	V;IMP
hoppe	hoppet	V;PST
nyfødt	nyfødt	ADJ;NEUT;SG
nyfødt	nyfødte	ADJ;DEF;SG+PL
forby	forbød	V;PST
forby	forbyr	V;PRS
forby	forby	V;IMP
forby	forbudt	V.PTCP;PST
demens	demensen	N;DEF;SG
fargerik	fargerike	ADJ;DEF;SG+PL
fargerik	fargerikt	ADJ;NEUT;SG
stryking	strykinga	N;DEF;SG
stryking	strykinger	N;NDEF;PL
stryking	strykingene	N;DEF;PL
syntetisk	syntetisk	ADJ;NEUT;SG
syntetisk	syntetiske	ADJ;DEF;SG+PL
komorer	komorerne	N;DEF;PL
komorer	komoreren	N;DEF;SG
komorer	komorere	N;NDEF;PL
rundkjøring	rundkjøringen	N;DEF;SG
rundkjøring	rundkjøringene	N;DEF;PL
rundkjøring	rundkjøringer	N;NDEF;PL
prins	prinsene	N;DEF;PL
prins	prinser	N;NDEF;PL
prins	prinsen	N;DEF;SG
destruere	destruert	V.PTCP;PST
destruere	destruer	V;IMP
destruere	destruerte	V;PST
destruere	destruerer	V;PRS
verdifull	verdifullt	ADJ;NEUT;SG
verdifull	verdifulle	ADJ;DEF;SG+PL
synke	sank	V;PST
synke	synk	V;IMP
synke	synker	V;PRS
synke	synkende	V.PTCP;PRS
synke	sunket	V.PTCP;PST
parlament	parlamentet	N;DEF;SG
parlament	parlamenter	N;NDEF;PL
parlament	parlamenta	N;DEF;PL
parlament	parlament	N;NDEF;PL
parlament	parlamentene	N;DEF;PL
lukker	lukkere	N;NDEF;PL
lukker	lukkeren	N;DEF;SG
lukker	lukkerne	N;DEF;PL
saltholdig	saltholdige	ADJ;DEF;SG+PL
saltholdig	saltholdig	ADJ;NEUT;SG
skyhøy	skyhøye	ADJ;DEF;SG+PL
skyhøy	skyhøyt	ADJ;NEUT;SG
kystlinje	kystlinja	N;DEF;SG
kystlinje	kystlinjer	N;NDEF;PL
kystlinje	kystlinjene	N;DEF;PL
suffiks	suffiks	N;NDEF;PL
suffiks	suffiksene	N;DEF;PL
suffiks	suffikset	N;DEF;SG
sketsj	sketsjen	N;DEF;SG
sketsj	sketsjer	N;NDEF;PL
sketsj	sketsjene	N;DEF;PL
hygienisk	hygienisk	ADJ;NEUT;SG
hygienisk	hygieniske	ADJ;DEF;SG+PL
forene	forent	V.PTCP;PST
forene	foren	V;IMP
forene	forente	V;PST
forene	forenende	V.PTCP;PRS
forene	forener	V;PRS
forene	forenet	V.PTCP;PST
segl	segla	N;DEF;PL
segl	segl	N;NDEF;PL
segl	seglet	N;DEF;SG
segl	seglene	N;DEF;PL
kontinuerlig	kontinuerlige	ADJ;DEF;SG+PL
kontinuerlig	kontinuerlig	ADJ;NEUT;SG
skyld	skyldene	N;DEF;PL
skyld	skylden	N;DEF;SG
skyld	skylder	N;NDEF;PL
syfilis	syfilisen	N;DEF;SG
piksel	pikselen	N;DEF;SG
piksel	piksler	N;NDEF;PL
piksel	pikslene	N;DEF;PL
art	arter	N;NDEF;PL
art	artene	N;DEF;PL
art	arten	N;DEF;SG
art	arta	N;DEF;SG
snakke	snakk	V;IMP
snakke	snakker	V;PRS
snakke	snakka	V;PST
litauer	litaueren	N;DEF;SG
litauer	litauerne	N;DEF;PL
litauer	litauere	N;NDEF;PL
gangbru	gangbruen	N;DEF;SG
gangbru	gangbruene	N;DEF;PL
gangbru	gangbrua	N;DEF;SG
gangbru	gangbruer	N;NDEF;PL
skinke	skinka	N;DEF;SG
skinke	skinkene	N;DEF;PL
skinke	skinker	N;NDEF;PL
beskjed	beskjeder	N;NDEF;PL
beskjed	beskjeden	N;DEF;SG
beskjed	beskjedene	N;DEF;PL
språk	språk	N;NDEF;PL
språk	språka	N;DEF;PL
språk	språket	N;DEF;SG
språk	språkene	N;DEF;PL
fisker	fiskeren	N;DEF;SG
fisker	fiskerne	N;DEF;PL
fisker	fiskere	N;NDEF;PL
begavelse	begavelser	N;NDEF;PL
begavelse	begavelsen	N;DEF;SG
begavelse	begavelsene	N;DEF;PL
tidsskrift	tidsskrifter	N;NDEF;PL
tidsskrift	tidsskrifta	N;DEF;PL
tidsskrift	tidsskriftet	N;DEF;SG
tidsskrift	tidsskrift	N;NDEF;PL
vaskeservant	vaskeservantene	N;DEF;PL
vaskeservant	vaskeservanter	N;NDEF;PL
vaskeservant	vaskeservanten	N;DEF;SG
diktatur	diktatura	N;DEF;PL
diktatur	diktatur	N;NDEF;PL
diktatur	diktaturet	N;DEF;SG
pakke	pakker	N;NDEF;PL
pakke	pakken	N;DEF;SG
pakke	pakkene	N;DEF;PL
pakke	pakka	N;DEF;SG
virksom	virksomt	ADJ;NEUT;SG
virksom	virksomme	ADJ;DEF;SG+PL
korridor	korridoren	N;DEF;SG
korridor	korridorer	N;NDEF;PL
korridor	korridorene	N;DEF;PL
perfekt	perfekt	ADJ;NEUT;SG
perfekt	perfekte	ADJ;DEF;SG+PL
sjonglør	sjongløren	N;DEF;SG
sjonglør	sjonglører	N;NDEF;PL
sjonglør	sjonglørene	N;DEF;PL
bibelsk	bibelsk	ADJ;NEUT;SG
bibelsk	bibelske	ADJ;DEF;SG+PL
matche	matcha	V;PST
matche	matcher	V;PRS
matche	matchende	V.PTCP;PRS
matche	match	V;IMP
dødfødt	dødfødte	ADJ;DEF;SG+PL
dødfødt	dødfødt	ADJ;NEUT;SG
ytringsfrihet	ytringsfriheta	N;DEF;SG
ytringsfrihet	ytringsfriheter	N;NDEF;PL
ytringsfrihet	ytringsfriheten	N;DEF;SG
ytringsfrihet	ytringsfrihetene	N;DEF;PL
viking	vikinger	N;NDEF;PL
viking	vikingen	N;DEF;SG
viking	vikingene	N;DEF;PL
fuktig	fuktig	ADJ;NEUT;SG
fuktig	fuktige	ADJ;DEF;SG+PL
fuktig	fuktigst	ADJ;SPRL;NDEF
fuktig	fuktigere	ADJ;CMPR
fuktig	fuktigste	ADJ;SPRL;DEF
renslighet	rensligheten	N;DEF;SG
renslighet	rensligheta	N;DEF;SG
bøtte	bøtter	N;NDEF;PL
bøtte	bøttene	N;DEF;PL
bøtte	bøtten	N;DEF;SG
bøtte	bøtta	N;DEF;SG
prisindeks	prisindeksen	N;DEF;SG
prisindeks	prisindekser	N;NDEF;PL
prisindeks	prisindeksene	N;DEF;PL
nå	nådd	V.PTCP;PST
nå	nå	V;IMP
nå	nådde	V;PST
nå	når	V;PRS
tastatur	tastaturer	N;NDEF;PL
tastatur	tastaturet	N;DEF;SG
tastatur	tastaturene	N;DEF;PL
tastatur	tastatura	N;DEF;PL
sykdom	sykdommene	N;DEF;PL
sykdom	sykdommen	N;DEF;SG
sykdom	sykdommer	N;NDEF;PL
egg	egga	N;DEF;PL
egg	egget	N;DEF;SG
egg	egg	N;NDEF;PL
hustru	hustruene	N;DEF;PL
hustru	hustruen	N;DEF;SG
hustru	hustruer	N;NDEF;PL
hustru	hustrua	N;DEF;SG
symbolsk	symbolsk	ADJ;NEUT;SG
symbolsk	symbolske	ADJ;DEF;SG+PL
førstehjelp	førstehjelpen	N;DEF;SG
etnisitet	etnisitetene	N;DEF;PL
etnisitet	etnisiteter	N;NDEF;PL
etnisitet	etnisiteten	N;DEF;SG
brikke	brikka	N;DEF;SG
brikke	brikkene	N;DEF;PL
brikke	brikker	N;NDEF;PL
barnesykdom	barnesykdommer	N;NDEF;PL
barnesykdom	barnesykdommene	N;DEF;PL
barnesykdom	barnesykdommen	N;DEF;SG
statussymbol	statussymboler	N;NDEF;PL
statussymbol	statussymbola	N;DEF;PL
statussymbol	statussymbolet	N;DEF;SG
symbol	symbola	N;DEF;PL
symbol	symbolet	N;DEF;SG
symbol	symbol	N;NDEF;PL
symbol	symbolene	N;DEF;PL
kjær	kjærest	ADJ;SPRL;NDEF
kjær	kjære	ADJ;DEF;SG+PL
kjær	kjært	ADJ;NEUT;SG
kjær	kjæreste	ADJ;SPRL;DEF
kjær	kjærere	ADJ;CMPR
mangle	mangla	V;PST
mangle	mangle	V;IMP
mangle	manglende	V.PTCP;PRS
mangle	mangler	V;PRS
mangle	manglet	V;PST
kartlegge	kartleggende	V.PTCP;PRS
kartlegge	kartlegg	V;IMP
kartlegge	kartlegger	V;PRS
kartlegge	kartla	V;PST
kartlegge	kartlagt	V.PTCP;PST
synd	synda	N;DEF;SG
synd	syndene	N;DEF;PL
synd	synden	N;DEF;SG
synd	synder	N;NDEF;PL
costaricaner	costaricanere	N;NDEF;PL
costaricaner	costaricaneren	N;DEF;SG
costaricaner	costaricanerne	N;DEF;PL
ikon	ikonen	N;DEF;SG
ikon	ikona	N;DEF;PL
ikon	ikon	N;NDEF;PL
ikon	ikoner	N;NDEF;PL
verdi	verdiene	N;DEF;PL
verdi	verdien	N;DEF;SG
verdi	verdier	N;NDEF;PL
huskatt	huskattene	N;DEF;PL
huskatt	huskatten	N;DEF;SG
huskatt	huskatter	N;NDEF;PL
dokumentmappe	dokumentmappa	N;DEF;SG
dokumentmappe	dokumentmapper	N;NDEF;PL
dokumentmappe	dokumentmappene	N;DEF;PL
berømt	berømt	ADJ;NEUT;SG
berømt	berømte	ADJ;DEF;SG+PL
pyramide	pyramidene	N;DEF;PL
pyramide	pyramiden	N;DEF;SG
pyramide	pyramider	N;NDEF;PL
posisjon	posisjonene	N;DEF;PL
posisjon	posisjonen	N;DEF;SG
posisjon	posisjoner	N;NDEF;PL
mager	magre	ADJ;DEF;SG+PL
mager	magert	ADJ;NEUT;SG
metropol	metropoler	N;NDEF;PL
metropol	metropolene	N;DEF;PL
metropol	metropolen	N;DEF;SG
barnelærdom	barnelærdomen	N;DEF;SG
barnelærdom	barnelærdomer	N;NDEF;PL
barnelærdom	barnelærdomene	N;DEF;PL
golf	golfer	N;NDEF;PL
golf	golfen	N;DEF;SG
golf	golfene	N;DEF;PL
utkonkurrere	utkonkurrer	V;IMP
utkonkurrere	utkonkurrerte	V;PST
utkonkurrere	utkonkurrert	V.PTCP;PST
utkonkurrere	utkonkurrerer	V;PRS
svarting	svartingen	N;DEF;SG
svarting	svartinger	N;NDEF;PL
svarting	svartingene	N;DEF;PL
botanisk	botanisk	ADJ;NEUT;SG
botanisk	botaniske	ADJ;DEF;SG+PL
kraft	kreftene	N;DEF;PL
kraft	krefter	N;NDEF;PL
kraft	krafta	N;DEF;SG
kraft	kraften	N;DEF;SG
kulturell	kulturelle	ADJ;DEF;SG+PL
kulturell	kulturelt	ADJ;NEUT;SG
frosset	frosset	ADJ;NEUT;SG
frosset	frosne	ADJ;DEF;SG+PL
søppel	søpla	N;DEF;SG
vannmølle	vannmøllene	N;DEF;PL
vannmølle	vannmølla	N;DEF;SG
vannmølle	vannmøller	N;NDEF;PL
nasjonalitet	nasjonaliteter	N;NDEF;PL
nasjonalitet	nasjonalitetene	N;DEF;PL
nasjonalitet	nasjonaliteten	N;DEF;SG
slektskap	slektskapa	N;DEF;PL
slektskap	slektskapen	N;DEF;SG
slektskap	slektskapene	N;DEF;PL
slektskap	slektskapet	N;DEF;SG
slektskap	slektskap	N;NDEF;PL
trone	trona	N;DEF;SG
trone	tronene	N;DEF;PL
trone	troner	N;NDEF;PL
omkrets	omkretsen	N;DEF;SG
omkrets	omkretsene	N;DEF;PL
omkrets	omkretser	N;NDEF;PL
servitør	servitørene	N;DEF;PL
servitør	servitøren	N;DEF;SG
servitør	servitører	N;NDEF;PL
edderkopp	edderkoppen	N;DEF;SG
edderkopp	edderkoppene	N;DEF;PL
edderkopp	edderkopper	N;NDEF;PL
revolver	revolvere	N;NDEF;PL
revolver	revolveren	N;DEF;SG
revolver	revolverne	N;DEF;PL
varemerke	varemerket	N;DEF;SG
varemerke	varemerker	N;NDEF;PL
varemerke	varemerkene	N;DEF;PL
sang	sangene	N;DEF;PL
sang	sanger	N;NDEF;PL
sang	sangen	N;DEF;SG
kristadelfianer	kristadelfianeren	N;DEF;SG
kristadelfianer	kristadelfianere	N;NDEF;PL
kristadelfianer	kristadelfianerne	N;DEF;PL
eksplosjon	eksplosjonen	N;DEF;SG
eksplosjon	eksplosjonene	N;DEF;PL
eksplosjon	eksplosjoner	N;NDEF;PL
ha	hadde	V;PST
ha	har	V;PRS
ha	ha	V;IMP
ha	hatt	V.PTCP;PST
perfeksjonist	perfeksjonistene	N;DEF;PL
perfeksjonist	perfeksjonister	N;NDEF;PL
perfeksjonist	perfeksjonisten	N;DEF;SG
legemlig	legemlig	ADJ;NEUT;SG
legemlig	legemlige	ADJ;DEF;SG+PL
bruk	bruken	N;DEF;SG
bruk	bruket	N;DEF;SG
sportslig	sportslig	ADJ;NEUT;SG
sportslig	sportslige	ADJ;DEF;SG+PL
burmeser	burmesere	N;NDEF;PL
burmeser	burmeserne	N;DEF;PL
burmeser	burmeseren	N;DEF;SG
flass	flass	N;NDEF;PL
flass	flasset	N;DEF;SG
flass	flassene	N;DEF;PL
flass	flassa	N;DEF;PL
istid	istida	N;DEF;SG
istid	istidene	N;DEF;PL
istid	istider	N;NDEF;PL
skål	skåla	N;DEF;SG
skål	skålene	N;DEF;PL
skål	skåler	N;NDEF;PL
skål	skålen	N;DEF;SG
garderobe	garderober	N;NDEF;PL
garderobe	garderobene	N;DEF;PL
garderobe	garderoben	N;DEF;SG
folkemusikk	folkemusikken	N;DEF;SG
tørst	tørstere	ADJ;CMPR
tørst	tørsteste	ADJ;SPRL;DEF
tørst	tørst	ADJ;NEUT;SG
tørst	tørste	ADJ;DEF;SG+PL
tørst	tørsten	N;DEF;SG
tørst	tørstest	ADJ;SPRL;NDEF
jordskjelv	jordskjelvene	N;DEF;PL
jordskjelv	jordskjelvet	N;DEF;SG
jordskjelv	jordskjelv	N;NDEF;PL
mutter	muttere	N;NDEF;PL
mutter	mutteren	N;DEF;SG
mutter	mutterne	N;DEF;PL
mutter	mutrene	N;DEF;PL
mutter	mutre	N;NDEF;PL
kvadratkilometer	kvadratkilometerne	N;DEF;PL
kvadratkilometer	kvadratkilometer	N;NDEF;PL
kvadratkilometer	kvadratkilometeren	N;DEF;SG
italiensk	italiensken	N;DEF;SG
italiensk	italienske	ADJ;DEF;SG+PL
italiensk	italiensk	ADJ;NEUT;SG
ukentlig	ukentlige	ADJ;DEF;SG+PL
ukentlig	ukentlig	ADJ;NEUT;SG
kvartal	kvartal	N;NDEF;PL
kvartal	kvartalene	N;DEF;PL
kvartal	kvartala	N;DEF;PL
kvartal	kvartaler	N;NDEF;PL
kvartal	kvartalet	N;DEF;SG
bekk	bekken	N;DEF;SG
bekk	bekkene	N;DEF;PL
bekk	bekker	N;NDEF;PL
viskositet	viskositeter	N;NDEF;PL
viskositet	viskositeten	N;DEF;SG
viskositet	viskositetene	N;DEF;PL
maler	maleren	N;DEF;SG
maler	malere	N;NDEF;PL
maler	malerne	N;DEF;PL
dele	deler	V;PRS
dele	del	V;IMP
dele	delt	V.PTCP;PST
dele	delte	V;PST
skrekkelig	skrekkelig	ADJ;NEUT;SG
skrekkelig	skrekkelige	ADJ;DEF;SG+PL
skrekkelig	skrekkeligst	ADJ;SPRL;NDEF
skrekkelig	skrekkeligste	ADJ;SPRL;DEF
skrekkelig	skrekkeligere	ADJ;CMPR
tredemølle	tredemølla	N;DEF;SG
tredemølle	tredemøllene	N;DEF;PL
tredemølle	tredemøllen	N;DEF;SG
tredemølle	tredemøller	N;NDEF;PL
syndebukk	syndebukkene	N;DEF;PL
syndebukk	syndebukken	N;DEF;SG
syndebukk	syndebukker	N;NDEF;PL
implisere	impliserte	V;PST
implisere	implisert	V.PTCP;PST
implisere	impliserer	V;PRS
implisere	impliser	V;IMP
implisere	impliserende	V.PTCP;PRS
mester	mestrer	N;NDEF;PL
mester	mesteren	N;DEF;SG
mester	mesterne	N;DEF;PL
mester	mestrene	N;DEF;PL
år	årene	N;DEF;PL
år	året	N;DEF;SG
år	år	N;NDEF;PL
flom	flommen	N;DEF;SG
flom	flommer	N;NDEF;PL
flom	flommene	N;DEF;PL
nordkoreaner	nordkoreanere	N;NDEF;PL
nordkoreaner	nordkoreaneren	N;DEF;SG
nordkoreaner	nordkoreanerne	N;DEF;PL
jordmor	jordmoren	N;DEF;SG
jordmor	jordmødrer	N;NDEF;PL
jordmor	jordmødrene	N;DEF;PL
jordmor	jordmødre	N;NDEF;PL
kubaner	kubanerne	N;DEF;PL
kubaner	kubaneren	N;DEF;SG
kubaner	kubanere	N;NDEF;PL
montenegriner	montenegrinerne	N;DEF;PL
montenegriner	montenegrinere	N;NDEF;PL
montenegriner	montenegrineren	N;DEF;SG
fortid	fortiden	N;DEF;SG
fortid	fortidene	N;DEF;PL
fortid	fortider	N;NDEF;PL
fortid	fortida	N;DEF;SG
sirkelsag	sirkelsagen	N;DEF;SG
sirkelsag	sirkelsager	N;NDEF;PL
sirkelsag	sirkelsagene	N;DEF;PL
hjelpsom	hjelpsomme	ADJ;DEF;SG+PL
hjelpsom	hjelpsomt	ADJ;NEUT;SG
frivillig	frivillige	ADJ;DEF;SG+PL
frivillig	frivillig	ADJ;NEUT;SG
enfoldig	enfoldige	ADJ;DEF;SG+PL
enfoldig	enfoldig	ADJ;NEUT;SG
plakk	plakket	N;DEF;SG
løselig	løselige	ADJ;DEF;SG+PL
løselig	løselig	ADJ;NEUT;SG
motvirke	motvirkende	V.PTCP;PRS
motvirke	motvirket	V;PST
motvirke	motvirker	V;PRS
motvirke	motvirk	V;IMP
motvirke	motvirka	V;PST
tablett	tabletter	N;NDEF;PL
tablett	tablettene	N;DEF;PL
tablett	tabletten	N;DEF;SG
singaporer	singaporerne	N;DEF;PL
singaporer	singaporere	N;NDEF;PL
singaporer	singaporeren	N;DEF;SG
algoritme	algoritmen	N;DEF;SG
algoritme	algoritmer	N;NDEF;PL
algoritme	algoritmene	N;DEF;PL
røyskatt	røyskatter	N;NDEF;PL
røyskatt	røyskattene	N;DEF;PL
røyskatt	røyskatten	N;DEF;SG
røyker	røykere	N;NDEF;PL
røyker	røykeren	N;DEF;SG
røyker	røykerne	N;DEF;PL
vitne	vitnene	N;DEF;PL
vitne	vitner	N;NDEF;PL
vitne	vitnet	N;DEF;SG
vitne	vitna	N;DEF;PL
torsdag	torsdager	N;NDEF;PL
torsdag	torsdagen	N;DEF;SG
torsdag	torsdagene	N;DEF;PL
reservoar	reservoarene	N;DEF;PL
reservoar	reservoaret	N;DEF;SG
reservoar	reservoar	N;NDEF;PL
lufthavn	lufthavna	N;DEF;SG
lufthavn	lufthavner	N;NDEF;PL
lufthavn	lufthavnene	N;DEF;PL
koordinasjon	koordinasjonen	N;DEF;SG
koordinasjon	koordinasjoner	N;NDEF;PL
koordinasjon	koordinasjonene	N;DEF;PL
fluid	fluidene	N;DEF;PL
fluid	fluid	N;NDEF;PL
fluid	fluidet	N;DEF;SG
fluid	fluida	N;DEF;PL
fluid	fluider	N;NDEF;PL
drake	drakene	N;DEF;PL
drake	draken	N;DEF;SG
drake	draker	N;NDEF;PL
sigarett	sigaretter	N;NDEF;PL
sigarett	sigarettene	N;DEF;SG
sigarett	sigaretten	N;DEF;SG
målestokk	målestokken	N;DEF;SG
målestokk	målestokkene	N;DEF;PL
målestokk	målestokker	N;NDEF;PL
diskvalifisere	diskvalifiser	V;IMP
diskvalifisere	diskvalifiserende	V.PTCP;PRS
diskvalifisere	diskvalifisert	V.PTCP;PST
diskvalifisere	diskvalifiserte	V;PST
diskvalifisere	diskvalifiserer	V;PRS
frigjøre	frigjør	V;IMP
frigjøre	frigjørende	V.PTCP;PRS
frigjøre	frigjort	V.PTCP;PST
frigjøre	frigjorde	V;PST
hakekors	hakekorsa	N;DEF;PL
hakekors	hakekorset	N;DEF;SG
hakekors	hakekors	N;NDEF;PL
brøk	brøker	N;NDEF;PL
brøk	brøken	N;DEF;SG
brøk	brøkene	N;DEF;PL
skihopper	skihoppere	N;NDEF;PL
skihopper	skihopperne	N;DEF;PL
skihopper	skihopperen	N;DEF;SG
ubegrenset	ubegrenset	ADJ;NEUT;SG
ubegrenset	ubegrensede	ADJ;DEF;SG+PL
ubegrenset	ubegrensete	ADJ;DEF;SG+PL
alternativ	alternative	ADJ;DEF;SG+PL
alternativ	alternativer	N;NDEF;PL
alternativ	alternativt	ADJ;NEUT;SG
alternativ	alternativa	N;DEF;PL
alternativ	alternativ	N;NDEF;PL
alternativ	alternativet	N;DEF;SG
kremere	kremerte	V;PST
kremere	kremert	V.PTCP;PST
kremere	kremerer	V;PRS
kremere	kremer	V;IMP
repertoar	repertoarene	N;DEF;PL
repertoar	repertoar	N;NDEF;PL
repertoar	repertoaret	N;DEF;SG
repertoar	repertoara	N;DEF;PL
årsdag	årsdagene	N;DEF;PL
årsdag	årsdager	N;NDEF;PL
årsdag	årsdagen	N;DEF;SG
plast	plastene	N;DEF;PL
plast	plasten	N;DEF;SG
plast	plaster	N;NDEF;PL
nauruer	nauruerne	N;DEF;PL
nauruer	naurueren	N;DEF;SG
nauruer	nauruere	N;NDEF;PL
kontekst	kontekster	N;NDEF;PL
kontekst	kontekstene	N;DEF;PL
kontekst	konteksten	N;DEF;SG
gordisk knute	den gordiske knuten	N;DEF;SG
milliardær	milliardæren	N;DEF;SG
milliardær	milliardærer	N;NDEF;PL
milliardær	milliardærene	N;DEF;PL
hundeeier	hundeeieren	N;DEF;SG
hundeeier	hundeeierne	N;DEF;PL
hundeeier	hundeeiere	N;NDEF;PL
gjenbruk	gjenbruken	N;DEF;SG
gjenbruk	gjenbruket	N;DEF;SG
høyteknologisk	høyteknologisk	ADJ;NEUT;SG
høyteknologisk	høyteknologiske	ADJ;DEF;SG+PL
fotball	fotballer	N;NDEF;PL
fotball	fotballene	N;DEF;PL
fotball	fotballen	N;DEF;SG
program	programmer	N;NDEF;PL
program	programma	N;DEF;PL
program	programmet	N;DEF;SG
program	programmene	N;DEF;PL
isolere	isolert	V.PTCP;PST
isolere	isolerte	V;PST
isolere	isoler	V;IMP
isolere	isolerer	V;PRS
isolere	isolerende	V.PTCP;PRS
rørsukker	rørsukkeret	N;DEF;SG
rapportere	rapporter	V;IMP
rapportere	rapporterer	V;PRS
rapportere	rapporterte	V;PST
rapportere	rapportert	V.PTCP;PST
rapportere	rapporterende	V.PTCP;PRS
alkoholholdig	alkoholholdige	ADJ;DEF;SG+PL
alkoholholdig	alkoholholdig	ADJ;NEUT;SG
halvøy	halvøyen	N;DEF;SG
halvøy	halvøyene	N;DEF;PL
halvøy	halvøyer	N;NDEF;PL
nyttårsdag	nyttårsdagen	N;DEF;SG
nyttårsdag	nyttårsdagene	N;DEF;PL
nyttårsdag	nyttårsdager	N;NDEF;PL
forskjellig	forskjellig	ADJ;NEUT;SG
forskjellig	forskjellige	ADJ;DEF;SG+PL
kvikksand	kvikksanden	N;DEF;SG
bevæpne	bevæpn	V;IMP
bevæpne	bevæpner	V;PRS
bevæpne	bevæpnet	V;PST
bevæpne	bevæpne	V;IMP
bore	bora	V;PST
bore	bor	V;IMP
bore	borer	V;PRS
bore	borende	V.PTCP;PRS
tilpasse	tilpasset	V;PST
tilpasse	tilpasser	V;PRS
tilpasse	tilpassende	V.PTCP;PRS
tilpasse	tilpass	V;IMP
tilpasse	tilpassa	V;PST
topphemmelig	topphemmelige	ADJ;DEF;SG+PL
topphemmelig	topphemmelig	ADJ;NEUT;SG
sterk	sterke	ADJ;DEF;SG+PL
sterk	sterkeste	ADJ;SPRL;DEF
sterk	sterkt	ADJ;NEUT;SG
sterk	sterkest	ADJ;SPRL;NDEF
sterk	sterkere	ADJ;CMPR
magedanserinne	magedanserinna	N;DEF;SG
magedanserinne	magedanserinner	N;NDEF;PL
magedanserinne	magedanserinnene	N;DEF;PL
forklaring	forklaringene	N;DEF;PL
forklaring	forklaringen	N;DEF;SG
forklaring	forklaringer	N;NDEF;PL
forklaring	forklaringa	N;DEF;SG
vegetariansk	vegetarianske	ADJ;DEF;SG+PL
vegetariansk	vegetariansk	ADJ;NEUT;SG
økotype	økotyper	N;NDEF;PL
økotype	økotypene	N;DEF;PL
økotype	økotypen	N;DEF;SG
dynetrekk	dynetrekkene	N;DEF;PL
dynetrekk	dynetrekk	N;NDEF;PL
dynetrekk	dynetrekka	N;DEF;PL
dynetrekk	dynetrekket	N;DEF;SG
forkortelse	forkortelsene	N;NDEF;PL
forkortelse	forkortelsen	N;DEF;SG
forkortelse	forkortelser	N;NDEF;PL
provins	provinsen	N;DEF;SG
provins	provinsene	N;DEF;PL
provins	provinser	N;NDEF;PL
skifte	skiftet	V;PST
skifte	skiftende	V.PTCP;PRS
skifte	skift	V;IMP
skifte	skifta	V;PST
skifte	skifter	V;PRS
ingenmannsland	ingenmannslandet	N;DEF;SG
onkel	onkler	N;NDEF;PL
onkel	onklene	N;DEF;PL
onkel	onkelen	N;DEF;SG
forhindre	forhindrer	V;PRS
forhindre	forhindret	V;PST
forhindre	forhindra	V;PST
forhindre	forhindre	V;IMP
forhindre	forhindr	V;IMP
fallskjerm	fallskjermer	N;NDEF;PL
fallskjerm	fallskjermene	N;DEF;PL
fallskjerm	fallskjermen	N;DEF;SG
dis	disen	N;DEF;SG
utelukke	utelukker	V;PRS
utelukke	utelukk	V;IMP
utelukke	utelukket	V;PST
utelukke	utelukka	V;PST
forandre	forandret	V;PST
forandre	forandr	V;IMP
forandre	forandrer	V;PRS
forandre	forandre	V;IMP
pryde	prydende	V.PTCP;PRS
pryde	pryder	V;PRS
pryde	pryda	V;PST
pryde	pryd	V;IMP
årtusen	årtusenet	N;DEF;SG
årtusen	årtusen	N;NDEF;PL
årtusen	årtusenene	N;DEF;PL
drøm	drømmene	N;DEF;PL
drøm	drømmer	N;NDEF;PL
drøm	drømmen	N;DEF;SG
perfeksjon	perfeksjonen	N;DEF;SG
perfeksjon	perfeksjoner	N;NDEF;PL
perfeksjon	perfeksjonene	N;DEF;PL
landsby	landsbyer	N;NDEF;PL
landsby	landsbyene	N;DEF;PL
landsby	landsbyen	N;DEF;SG
None	stås	V;PRS;PASS
None	stå	V;NFIN;ACT
None	står	V;PRS;ACT
None	stås	V;NFIN;PASS
None	ødelagt	V.PTCP;PST
None	stånde	V.PTCP;PRS
None	ødelegg	V;IMP
None	ødela	V;PST
None	ødeleggende	V.PTCP;PRS
None	ødelegges	V;PRS;PASS
None	ødelegger	V;PRS;ACT
oljemaleri	oljemaleria	N;DEF;PL
oljemaleri	oljemaleriet	N;DEF;SG
oljemaleri	oljemalerier	N;NDEF;PL
oljemaleri	oljemaleriene	N;DEF;PL
oljemaleri	oljemaleri	N;NDEF;PL
brødrister	brødristeren	N;DEF;SG
brødrister	brødristere	N;NDEF;PL
brødrister	brødristerne	N;DEF;PL
bronkitt	bronkitten	N;DEF;SG
bronkitt	bronkitter	N;NDEF;PL
bronkitt	bronkittene	N;DEF;PL
rød dag	røde dager	N;PL
troll	trollet	N;DEF;SG
troll	trollene	N;DEF;PL
troll	troll	N;NDEF;PL
troll	trolla	N;DEF;PL
kolonne	kolonnen	N;DEF;SG
kolonne	kolonner	N;NDEF;PL
kolonne	kolonnene	N;DEF;PL
bilkø	bilkøene	N;DEF;PL
bilkø	bilkøen	N;DEF;SG
bilkø	bilkøer	N;NDEF;PL
skuespill	skuespill	N;NDEF;PL
skuespill	skuespillet	N;DEF;SG
skuespill	skuespillene	N;DEF;PL
silisium	silisiumet	N;DEF;SG
blindpassasjer	blindpassasjerer	N;NDEF;PL
blindpassasjer	blindpassasjerene	N;DEF;PL
blindpassasjer	blindpassasjeren	N;DEF;SG
brenne	brenn	V;IMP
brenne	brent	V.PTCP;PST
brenne	brennende	V.PTCP;PRS
brenne	brant	V;PST
brenne	brenner	V;PRS
statistisk	statistisk	ADJ;NEUT;SG
statistisk	statistiske	ADJ;DEF;SG+PL
forstad	forstedene	N;DEF;PL
forstad	forsteder	N;NDEF;PL
forstad	forstaden	N;DEF;SG
totalitær	totalitært	ADJ;NEUT;SG
totalitær	totalitære	ADJ;DEF;SG+PL
tyngdekraft	tyngdekreftene	N;DEF;PL
tyngdekraft	tyngdekraften	N;DEF;SG
tyngdekraft	tyngdekrefter	N;NDEF;PL
tyngdekraft	tyngdekrafta	N;DEF;SG
kran	kranene	N;DEF;PL
kran	kraner	N;NDEF;PL
kran	krana	N;DEF;SG
kran	kranen	N;DEF;SG
frukthage	frukthagen	N;DEF;SG
frukthage	frukthagene	N;DEF;PL
frukthage	frukthager	N;NDEF;PL
komfyr	komfyrer	N;NDEF;PL
komfyr	komfyrene	N;DEF;PL
komfyr	komfyren	N;DEF;SG
fiken	fikener	N;NDEF;PL
fiken	fikenen	N;DEF;SG
fiken	fikenene	N;DEF;PL
forkjølelse	forkjølelsene	N;DEF;PL
forkjølelse	forkjølelser	N;NDEF;PL
forkjølelse	forkjølelsen	N;DEF;SG
verdensmesterskap	verdensmesterskaper	N;NDEF;PL
verdensmesterskap	verdensmesterskapet	N;DEF;SG
verdensmesterskap	verdensmesterskapa	N;DEF;PL
verdensmesterskap	verdensmesterskapene	N;DEF;PL
tilskuer	tilskueren	N;DEF;SG
tilskuer	tilskuerne	N;DEF;PL
tilskuer	tilskuere	N;NDEF;PL
kartografi	kartografien	N;DEF;SG
klær	klærne	N;DEF;PL
håndfull	håndfuller	N;NDEF;PL
håndfull	håndfullen	N;DEF;SG
håndfull	håndfullene	N;DEF;PL
ambisjon	ambisjoner	N;NDEF;PL
ambisjon	ambisjonen	N;DEF;SG
ambisjon	ambisjonene	N;DEF;PL
epidemisk	epidemiske	ADJ;DEF;SG+PL
epidemisk	epidemisk	ADJ;NEUT;SG
konisk	konisk	ADJ;NEUT;SG
konisk	koniske	ADJ;DEF;SG+PL
forbindelse	forbindelser	N;NDEF;PL
forbindelse	forbindelsene	N;DEF;PL
forbindelse	forbindelsen	N;DEF;SG
million	millionene	N;DEF;PL
million	millioner	N;NDEF;PL
million	millionen	N;DEF;SG
oppdage	oppdag	V;IMP
oppdage	oppdaget	V;PST
oppdage	oppdager	V;PRS
oppdage	oppdagende	V.PTCP;PRS
forord	forord	N;NDEF;PL
forord	forordet	N;DEF;SG
forord	fororda	N;DEF;PL
forord	forordene	N;DEF;PL
stykke	stykker	N;NDEF;PL
stykke	stykket	N;DEF;SG
stykke	stykkene	N;DEF;PL
albatross	albatrossen	N;DEF;SG
albatross	albatrossene	N;DEF;PL
albatross	albatrosser	N;NDEF;PL
lett	lett	ADJ;NEUT;SG
lett	lette	ADJ;DEF;SG+PL
lett	letteste	ADJ;SPRL;DEF
lett	lettere	ADJ;CMPR
lett	lettest	ADJ;SPRL;NDEF
skinn	skinnene	N;DEF;PL
skinn	skinnet	N;DEF;SG
skinn	skinn	N;NDEF;PL
skinn	skinna	N;DEF;PL
finne opp	fant opp	V;PST
finne opp	finner opp	V;PRS
finne opp	finn opp	V;IMP
finne opp	funnet opp	V.PTCP;PST
sammenligne	sammenlignende	V.PTCP;PRS
sammenligne	sammenlignet	V;PST
sammenligne	sammenligna	V;PST
sammenligne	sammenlign	V;IMP
hunn	hunnen	N;DEF;SG
hunn	hunner	N;NDEF;PL
hunn	hunnene	N;DEF;PL
uvennlig	uvennlig	ADJ;NEUT;SG
uvennlig	uvennlige	ADJ;DEF;SG+PL
galskap	galskapen	N;DEF;SG
galskap	galskaper	N;NDEF;PL
galskap	galskapene	N;DEF;PL
radioaktiv	radioaktivt	ADJ;NEUT;SG
radioaktiv	radioaktive	ADJ;DEF;SG+PL
vital	vitale	ADJ;DEF;SG+PL
vital	vitalt	ADJ;NEUT;SG
nypotet	nypoteter	N;NDEF;PL
nypotet	nypotetene	N;DEF;PL
nypotet	nypoteten	N;DEF;SG
dataprogram	dataprogramma	N;DEF;PL
dataprogram	dataprogram	N;NDEF;PL
dataprogram	dataprogrammet	N;DEF;SG
dataprogram	dataprogrammene	N;DEF;PL
dataprogram	dataprogrammer	N;NDEF;PL
fortau	fortaua	N;DEF;PL
fortau	fortauet	N;DEF;SG
fortau	fortauer	N;NDEF;PL
fortau	fortauene	N;DEF;PL
fortau	fortau	N;NDEF;PL
hode	hodet	N;DEF;SG
hode	hodene	N;DEF;PL
hode	hoder	N;NDEF;PL
hode	hoda	N;DEF;PL
fugleliv	fuglelivet	N;DEF;SG
fattig	fattige	ADJ;DEF;SG+PL
fattig	fattigste	ADJ;SPRL;DEF
fattig	fattigst	ADJ;SPRL;NDEF
fattig	fattig	ADJ;NEUT;SG
fattig	fattigere	ADJ;CMPR
tidel	tidelene	N;DEF;PL
tidel	tideler	N;NDEF;PL
tidel	tidelen	N;DEF;SG
blindeskrift	blindeskriften	N;DEF;SG
hinne	hinner	N;NDEF;PL
hinne	hinna	N;DEF;SG
hinne	hinnene	N;DEF;PL
sol	solene	N;DEF;PL
sol	soler	N;NDEF;PL
sol	solen	N;DEF;SG
millionær	millionæren	N;DEF;SG
millionær	millionærer	N;NDEF;PL
millionær	millionærene	N;DEF;PL
behandling	behandlinger	N;NDEF;PL
behandling	behandlinga	N;DEF;SG
behandling	behandlingen	N;DEF;SG
behandling	behandlingene	N;DEF;PL
saltvann	saltvannet	N;DEF;SG
kreere	kreerte	V;PST
kreere	kreerer	V;PRS
kreere	kreer	V;IMP
kreere	kreerende	V.PTCP;PRS
kreere	kreert	V.PTCP;PST
univers	universene	N;DEF;PL
univers	universet	N;DEF;SG
univers	univers	N;NDEF;PL
univers	universer	N;NDEF;PL
univers	universa	N;DEF;PL
uforandret	uforandret	ADJ;NEUT;SG
uforandret	uforandrede	ADJ;DEF;SG+PL
vindmølle	vindmøllene	N;DEF;PL
vindmølle	vindmøller	N;NDEF;PL
vindmølle	vindmøllen	N;DEF;SG
vindmølle	vindmølla	N;DEF;SG
symptom	symptomene	N;DEF;PL
symptom	symptom	N;NDEF;PL
symptom	symptomet	N;DEF;SG
polsk	polsken	N;DEF;SG
polsk	polske	ADJ;DEF;SG+PL
polsk	polsk	ADJ;NEUT;SG
skulle	skal	V;PRS
skulle	skullet	V.PTCP;PST
skulle	skulle	V;PST
hårklipp	hårklipper	N;NDEF;PL
hårklipp	hårklippene	N;DEF;PL
hårklipp	hårklippen	N;DEF;SG
edelsten	edelstenene	N;DEF;PL
edelsten	edelstener	N;NDEF;PL
edelsten	edelstenen	N;DEF;SG
knallsyre	knallsyren	N;DEF;SG
knallsyre	knallsyra	N;DEF;SG
veg	veger	N;NDEF;PL
veg	vegene	N;DEF;PL
veg	vegen	N;DEF;SG
tjern	tjernene	N;DEF;PL
tjern	tjernen	N;DEF;SG
tjern	tjern	N;NDEF;PL
tjern	tjerna	N;DEF;PL
tjern	tjerner	N;NDEF;PL
tjern	tjernet	N;DEF;SG
bety	betydd	V.PTCP;PST
bety	bety	V;IMP
bety	betydde	V;PST
bety	betød	V;PST
bety	betyr	V;PRS
myte	myter	N;NDEF;PL
myte	myten	N;DEF;SG
myte	mytene	N;DEF;PL
liturgisk	liturgiske	ADJ;DEF;SG+PL
liturgisk	liturgisk	ADJ;NEUT;SG
monarki	monarkia	N;DEF;PL
monarki	monarkier	N;NDEF;PL
monarki	monarkiet	N;DEF;SG
abbed	abbedene	N;DEF;PL
abbed	abbeden	N;DEF;SG
abbed	abbeder	N;NDEF;PL
kvadratisk	kvadratiske	ADJ;DEF;SG+PL
kvadratisk	kvadratisk	ADJ;NEUT;SG
symbolisere	symboliserer	V;PRS
symbolisere	symbolisert	V.PTCP;PST
symbolisere	symboliserte	V;PST
symbolisere	symboliser	V;IMP
appelsintre	appelsintrærne	N;DEF;PL
appelsintre	appelsintre	N;NDEF;PL
appelsintre	appelsintrær	N;NDEF;PL
appelsintre	appelsintreet	N;DEF;SG
periodesystem	periodesystemet	N;DEF;SG
jordskred	jordskredene	N;DEF;PL
jordskred	jordskredet	N;DEF;SG
jordskred	jordskred	N;NDEF;PL
jordskred	jordskreda	N;DEF;PL
uvilkårlig	uvilkårlig	ADJ;NEUT;SG
uvilkårlig	uvilkårlige	ADJ;DEF;SG+PL
gruvearbeider	gruvearbeiderne	N;DEF;PL
gruvearbeider	gruvearbeideren	N;DEF;SG
gruvearbeider	gruvearbeidere	N;NDEF;PL
hårbørste	hårbørster	N;NDEF;PL
hårbørste	hårbørsten	N;DEF;SG
hårbørste	hårbørstene	N;DEF;PL
punktlig	punktlige	ADJ;DEF;SG+PL
punktlig	punktlig	ADJ;NEUT;SG
appetitt	appetitten	N;DEF;SG
addisjon	addisjonen	N;DEF;SG
addisjon	addisjonene	N;DEF;PL
addisjon	addisjoner	N;NDEF;PL
redigere	redigerer	V;PRS
redigere	redigerte	V;PST
redigere	redigerende	V.PTCP;PRS
redigere	rediger	V;IMP
redigere	redigert	V.PTCP;PST
melasse	melassen	N;DEF;SG
meningsløs	meningsløse	ADJ;DEF;SG+PL
meningsløs	meningsløst	ADJ;NEUT;SG
nerve	nerven	N;DEF;SG
nerve	nervene	N;DEF;PL
nerve	nerver	N;NDEF;PL
folie	folier	N;NDEF;PL
folie	foliene	N;DEF;PL
folie	folien	N;DEF;SG
gammel	gamle	ADJ;DEF;SG+PL
gammel	eldste	ADJ;SPRL;DEF
gammel	gammelt	ADJ;NEUT;SG
gammel	eldre	ADJ;CMPR
gammel	eldst	ADJ;SPRL;NDEF
skarlagen	skarlagena	N;DEF;PL
skarlagen	skarlagenet	N;DEF;SG
skarlagen	skarlagen	N;NDEF;PL
gruppe	gruppene	N;DEF;PL
gruppe	gruppa	N;DEF;SG
gruppe	grupper	N;NDEF;PL
gruppe	gruppen	N;DEF;SG
forhandling	forhandlinger	N;NDEF;PL
forhandling	forhandlingene	N;DEF;PL
forhandling	forhandlinga	N;DEF;SG
tisse	tissa	V;PST
tisse	tiss	V;IMP
tisse	tisser	V;PRS
tisse	tisset	V;PST
sperrebånd	sperrebånda	N;DEF;PL
sperrebånd	sperrebånd	N;NDEF;PL
sperrebånd	sperrebåndene	N;DEF;PL
sperrebånd	sperrebåndet	N;DEF;SG
teppe	teppet	N;DEF;SG
teppe	teppa	N;DEF;PL
teppe	tepper	N;NDEF;PL
teppe	teppene	N;DEF;PL
skjønn	skjønne	ADJ;DEF;SG+PL
skjønn	skjønt	ADJ;NEUT;SG
kule	kulen	N;DEF;SG
kule	kuler	N;NDEF;PL
kule	kulene	N;DEF;PL
stengel	stenglene	N;DEF;PL
stengel	stengler	N;NDEF;PL
stengel	stengelen	N;DEF;SG
verdiløs	verdiløse	ADJ;DEF;SG+PL
verdiløs	verdiløst	ADJ;NEUT;SG
inndele	inndeler	V;PRS
inndele	inndelte	V;PST
inndele	inndelt	V.PTCP;PST
inndele	inndel	V;IMP
blasfemi	blasfemien	N;DEF;SG
ibenholt	ibenholten	N;DEF;SG
ibenholt	ibenholtet	N;DEF;SG
male	mal	V;IMP
male	malt	V.PTCP;PST
male	maler	V;PRS
male	malende	V.PTCP;PRS
male	malte	V;PST
vokabular	vokabularer	N;NDEF;PL
vokabular	vokabularet	N;DEF;SG
vokabular	vokabulara	N;DEF;PL
vokabular	vokabularene	N;DEF;PL
autoritet	autoriteter	N;NDEF;PL
autoritet	autoritetene	N;DEF;PL
autoritet	autoriteten	N;DEF;SG
halvautomatisk	halvautomatiske	ADJ;DEF;SG+PL
halvautomatisk	halvautomatisk	ADJ;NEUT;SG
tvetydig	tvetydige	ADJ;DEF;PL
tvetydig	tvetydig	ADJ;NEUT
bru	brua	N;DEF;SG
bru	bruer	N;NDEF;PL
bru	bruene	N;DEF;PL
bru	bruen	N;DEF;SG
morgen	morgener	N;NDEF;PL
morgen	morgenen	N;DEF;SG
morgen	morgenene	N;DEF;PL
ingefærøl	ingefærølet	N;DEF;SG
gammastråling	gammastrålingen	N;DEF;SG
gammastråling	gammastrålinga	N;DEF;SG
løsne	løsnet	V;PST
løsne	løsner	V;PRS
løsne	løsn	V;IMP
påvirke	påvirk	V;IMP
påvirke	påvirker	V;PRS
påvirke	påvirket	V;PST
himmel	himmelen	N;DEF;SG
himmel	himler	N;NDEF;PL
himmel	himlene	N;DEF;PL
sølvtøy	sølvtøyet	N;DEF;SG
brorskap	brorskapa	N;DEF;PL
brorskap	brorskaper	N;NDEF;PL
brorskap	brorskapene	N;DEF;PL
brorskap	brorskap	N;NDEF;PL
brorskap	brorskapet	N;DEF;SG
størrelse	størrelser	N;NDEF;PL
størrelse	størrelsen	N;DEF;SG
størrelse	størrelsene	N;DEF;PL
seksdel	seksdeler	N;NDEF;PL
seksdel	seksdelen	N;DEF;SG
seksdel	seksdelene	N;DEF;PL
produsere	produsert	V.PTCP;PST
produsere	produserte	V;PST
produsere	produser	V;IMP
produsere	produserer	V;PRS
komedie	komediene	N;DEF;PL
komedie	komedier	N;NDEF;PL
komedie	komedien	N;DEF;SG
brett	brettene	N;DEF;PL
brett	brett	N;NDEF;PL
brett	brettet	N;DEF;SG
brett	bretter	N;NDEF;PL
brett	bretta	N;DEF;PL
fjerdedel	fjerdedelene	N;DEF;PL
fjerdedel	fjerdedelen	N;DEF;SG
fjerdedel	fjerdedeler	N;NDEF;PL
pessimist	pessimistene	N;DEF;PL
pessimist	pessimisten	N;DEF;SG
pessimist	pessimister	N;NDEF;PL
natriumklorid	natriumkloridet	N;DEF;SG
gren	grener	N;NDEF;PL
gren	grenene	N;DEF;PL
gren	grenen	N;DEF;SG
gren	grena	N;DEF;SG
flyte	fløyt	V;PST
flyte	flyt	V;IMP
flyte	flytende	V.PTCP;PRS
flyte	flytt	V.PTCP;PST
flyte	fløt	V;PST
flyte	flyter	V;PRS
krasje	krasjet	V;PST
krasje	krasjer	V;PRS
krasje	krasjende	V.PTCP;PRS
krasje	krasj	V;IMP
krasje	krasja	V;PST
justerbar	justerbare	ADJ;DEF;SG+PL
justerbar	justerbart	ADJ;NEUT;SG
massiv	massivt	ADJ;NEUT;SG
massiv	massive	ADJ;DEF;SG+PL
kunde	kunden	N;DEF;SG
kunde	kundene	N;DEF;PL
kunde	kunder	N;NDEF;PL
dikter	diktere	N;NDEF;PL
dikter	dikterne	N;DEF;PL
dikter	dikteren	N;DEF;SG
beniner	beninere	N;NDEF;PL
beniner	benineren	N;DEF;SG
beniner	beninerne	N;DEF;PL
madagasser	madagassere	N;NDEF;PL
madagasser	madagasseren	N;DEF;SG
madagasser	madagasserne	N;DEF;PL
jernbanelinje	jernbanelinjer	N;NDEF;PL
jernbanelinje	jernbanelinjen	N;DEF;SG
jernbanelinje	jernbanelinja	N;DEF;SG
jernbanelinje	jernbanelinjene	N;DEF;PL
råtne	råtna	V;PST
råtne	råtne	V;IMP
råtne	råtner	V;PRS
råtne	råtnende	V.PTCP;PRS
autisme	autismen	N;DEF;SG
skjegg	skjegg	N;NDEF;PL
skjegg	skjeggene	N;DEF;PL
skjegg	skjegget	N;DEF;SG
skjegg	skjegga	N;DEF;PL
sprengstoff	sprengstoffet	N;DEF;SG
sprengstoff	sprengstoff	N;NDEF;PL
sprengstoff	sprengstoffa	N;DEF;PL
sprengstoff	sprengstoffene	N;DEF;PL
indonesier	indonesierne	N;DEF;PL
indonesier	indonesiere	N;NDEF;PL
indonesier	indonesieren	N;DEF;SG
dogme	dogmene	N;DEF;PL
dogme	dogmet	N;DEF;SG
dogme	dogmer	N;NDEF;PL
dogme	dogma	N;DEF;PL
luksuriøs	luksuriøst	ADJ;NEUT;SG
luksuriøs	luksuriøse	ADJ;DEF;SG+PL
akustisk	akustisk	ADJ;NEUT;SG
akustisk	akustiske	ADJ;DEF;SG+PL
snømåke	snømåkene	N;DEF;PL
snømåke	snømåker	N;NDEF;PL
snømåke	snømåka	N;DEF;SG
kurder	kurderne	N;DEF;PL
kurder	kurdere	N;NDEF;PL
kurder	kurderen	N;DEF;SG
komiker	komikerne	N;DEF;PL
komiker	komikere	N;NDEF;PL
komiker	komikeren	N;DEF;SG
automat	automatene	N;DEF;PL
automat	automaten	N;DEF;SG
automat	automater	N;NDEF;PL
navlestreng	navlestrengen	N;DEF;SG
navlestreng	navlestrenger	N;NDEF;PL
navlestreng	navlestrengene	N;DEF;PL
kommersiell	kommersielt	ADJ;NEUT;SG
kommersiell	kommersielle	ADJ;DEF;SG+PL
bredde	bredder	N;NDEF;PL
bredde	breddene	N;DEF;PL
bredde	bredden	N;DEF;SG
tefat	tefater	N;NDEF;PL
tefat	tefatene	N;DEF;PL
tefat	tefatet	N;DEF;SG
horde	horder	N;NDEF;PL
horde	horden	N;DEF;SG
horde	hordene	N;DEF;PL
dobbelthake	dobbelthaker	N;NDEF;PL
dobbelthake	dobbelthaken	N;DEF;SG
dobbelthake	dobbelthakene	N;DEF;PL
attraksjon	attraksjoner	N;NDEF;PL
attraksjon	attraksjonene	N;DEF;PL
attraksjon	attraksjonen	N;DEF;SG
nedgradere	nedgraderte	V;PST
nedgradere	nedgrader	V;IMP
nedgradere	nedgraderende	V.PTCP;PRS
nedgradere	nedgraderer	V;PRS
nedgradere	nedgradert	V.PTCP;PST
skjermutskrift	skjermutskriftene	N;DEF;PL
skjermutskrift	skjermutskrifta	N;DEF;SG
skjermutskrift	skjermutskrifter	N;NDEF;PL
skjermutskrift	skjermutskriften	N;DEF;SG
bygdelag	bygdelagene	N;DEF;PL
bygdelag	bygdelaget	N;DEF;SG
bygdelag	bygdelag	N;NDEF;PL
bygdelag	bygdelaga	N;DEF;PL
forhold	forholda	N;DEF;PL
forhold	forhold	N;NDEF;PL
forhold	forholdet	N;DEF;SG
tresleiv	tresleiva	N;DEF;SG
tresleiv	tresleivene	N;DEF;PL
tresleiv	tresleiver	N;NDEF;PL
aluminiumsfolie	aluminiumsfolien	N;DEF;SG
aluminiumsfolie	aluminiumsfoliene	N;DEF;PL
aluminiumsfolie	aluminiumsfolier	N;NDEF;PL
bakke	bakken	N;DEF;SG
bakke	bakkene	N;DEF;PL
bakke	bakker	N;NDEF;PL
gotisk	gotiske	ADJ;DEF;SG+PL
gotisk	gotisk	ADJ;NEUT;SG
marked	marked	N;NDEF;PL
marked	markedene	N;DEF;PL
marked	markedet	N;DEF;SG
marked	markeder	N;NDEF;PL
kreativitet	kreativiteten	N;DEF;SG
kongerike	kongerika	N;DEF;PL
kongerike	kongeriker	N;NDEF;PL
kongerike	kongeriket	N;DEF;SG
kongerike	kongerikene	N;DEF;PL
fruktbar	fruktbare	ADJ;DEF;SG+PL
fruktbar	fruktbart	ADJ;NEUT;SG
biskop	biskoper	N;NDEF;PL
biskop	biskopene	N;DEF;PL
biskop	biskopen	N;DEF;SG
halvkule	halvkula	N;DEF;SG
halvkule	halvkulene	N;DEF;PL
halvkule	halvkuler	N;NDEF;PL
or	oren	N;DEF;SG
or	orene	N;DEF;PL
or	orer	N;NDEF;PL
skjære	skjær	V;IMP
skjære	skar	V;PST
skjære	skåret	V.PTCP;PST
skjære	skjærer	N;NDEF;PL
skjære	skjærene	N;DEF;PL
skjære	skjæren	N;DEF;SG
skjære	skjærer	V;PRS
skjære	skjæra	N;DEF;SG
presentasjon	presentasjonene	N;DEF;PL
presentasjon	presentasjoner	N;NDEF;PL
presentasjon	presentasjonen	N;DEF;SG
steinblokk	steinblokker	N;NDEF;PL
steinblokk	steinblokken	N;DEF;SG
steinblokk	steinblokkene	N;DEF;PL
hengebro	hengebroen	N;DEF;SG
hengebro	hengebroene	N;DEF;PL
hengebro	hengebroer	N;NDEF;PL
dødsdømt	dødsdømte	ADJ;DEF;SG+PL
dødsdømt	dødsdømt	ADJ;NEUT;SG
lugar	lugaren	N;DEF;SG
lugar	lugarer	N;NDEF;PL
lugar	lugarene	N;DEF;PL
vitsemaker	vitsemakerne	N;DEF;PL
vitsemaker	vitsemakere	N;NDEF;PL
vitsemaker	vitsemakeren	N;DEF;SG
månedlig	månedlig	ADJ;NEUT;SG
månedlig	månedlige	ADJ;DEF;SG+PL
snøbrett	snøbrettet	N;DEF;SG
snøbrett	snøbrettene	N;DEF;PL
snøbrett	snøbrett	N;NDEF;PL
snøbrett	snøbretta	N;DEF;PL
islandsk	islandsken	N;DEF;SG
islandsk	islandsk	ADJ;NEUT;SG
islandsk	islandske	ADJ;DEF;SG+PL
fanatisk	fanatisk	ADJ;NEUT;SG
fanatisk	fanatiske	ADJ;DEF;SG+PL
opprinnelse	opprinnelsene	N;DEF;PL
opprinnelse	opprinnelsen	N;DEF;SG
opprinnelse	opprinnelser	N;NDEF;PL
ferdig	ferdige	ADJ;DEF;SG+PL
ferdig	ferdig	ADJ;NEUT;SG
uidentifisert	uidentifisert	ADJ;NEUT;SG
uidentifisert	uidentifiserte	ADJ;DEF;SG+PL
forekomst	forekomster	N;NDEF;PL
forekomst	forekomsten	N;DEF;SG
forekomst	forekomstene	N;DEF;PL
utstillingsdukke	utstillingsdukkene	N;DEF;PL
utstillingsdukke	utstillingsdukker	N;NDEF;PL
utstillingsdukke	utstillingsdukken	N;DEF;SG
forandring	forandringene	N;DEF;PL
forandring	forandringen	N;DEF;SG
forandring	forandringer	N;NDEF;PL
gasse	gasser	N;NDEF;PL
gasse	gassen	N;DEF;SG
gasse	gassene	N;DEF;PL
nymfomani	nymfomanien	N;DEF;SG
nivå	nivået	N;DEF;SG
nivå	nivåene	N;DEF;PL
nivå	nivå	N;NDEF;PL
nivå	nivåer	N;NDEF;PL
nivå	nivåa	N;DEF;PL
portugisisk	portugisisk	ADJ;NEUT;SG
portugisisk	portugisiske	ADJ;DEF;SG+PL
portugisisk	portugisisken	N;DEF;SG
prinsesse	prinsessen	N;DEF;SG
prinsesse	prinsesser	N;NDEF;PL
prinsesse	prinsessene	N;DEF;PL
prinsesse	prinsessa	N;DEF;SG
radio	radioer	N;NDEF;PL
radio	radioen	N;DEF;SG
radio	radioene	N;DEF;PL
kurdisk	kurdisk	ADJ;NEUT;SG
kurdisk	kurdiske	ADJ;DEF;SG+PL
blomsterbed	blomsterbedet	N;DEF;SG
blomsterbed	blomsterbed	N;NDEF;PL
blomsterbed	blomsterbeda	N;DEF;PL
gi	gav	V;PST
gi	gitt	V.PTCP;PST
gi	gir	V;PRS
gi	gi	V;IMP
gi	ga	V;PST
primær	primært	ADJ;NEUT;SG
primær	primære	ADJ;DEF;SG+PL
bueskytter	bueskyttere	N;NDEF;PL
bueskytter	bueskytterne	N;DEF;PL
bueskytter	bueskytteren	N;DEF;SG
ekspedisjon	ekspedisjonen	N;DEF;SG
ekspedisjon	ekspedisjonene	N;DEF;PL
ekspedisjon	ekspedisjoner	N;NDEF;PL
finlender	finlenderen	N;DEF;SG
finlender	finlenderne	N;DEF;PL
finlender	finlendere	N;NDEF;PL
tonn	tonnene	N;DEF;PL
tonn	tonn	N;NDEF;PL
tonn	tonna	N;DEF;PL
tonn	tonnet	N;DEF;SG
firedoble	firedobler	V;PRS
firedoble	firedoblet	V;PST
firedoble	firedobl	V;IMP
firedoble	firedoble	V;IMP
firedoble	firedobla	V;PST
salomoner	salomonere	N;NDEF;PL
salomoner	salomonerne	N;DEF;PL
salomoner	salomoneren	N;DEF;SG
sanktlusianer	sanktlusianere	N;NDEF;PL
sanktlusianer	sanktlusianeren	N;DEF;SG
sanktlusianer	sanktlusianerne	N;DEF;PL
stenge	stengte	V;PST
stenge	steng	V;IMP
stenge	stenger	V;PRS
stenge	stengt	V.PTCP;PST
levering	leveringen	N;DEF;SG
levering	leveringene	N;DEF;PL
levering	leveringer	N;NDEF;PL
levering	leveringa	N;DEF;SG
jødisk	jødiske	ADJ;DEF;SG+PL
jødisk	jødisk	ADJ;NEUT;SG
venezuelaner	venezuelanere	N;NDEF;PL
venezuelaner	venezuelaneren	N;DEF;SG
venezuelaner	venezuelanerne	N;DEF;PL
bryllupskake	bryllupskaka	N;DEF;SG
bryllupskake	bryllupskakene	N;DEF;PL
bryllupskake	bryllupskaker	N;NDEF;PL
hertugdømme	hertugdømmet	N;DEF;SG
hertugdømme	hertugdømmene	N;DEF;PL
hertugdømme	hertugdømmer	N;NDEF;PL
hertugdømme	hertugdømma	N;DEF;PL
sjømann	sjømannen	N;DEF;SG
sjømann	sjømennene	N;DEF;PL
sjømann	sjømenn	N;NDEF;PL
spiralfjær	spiralfjær	N;NDEF;PL
spiralfjær	spiralfjærene	N;DEF;PL
spiralfjær	spiralfjæren	N;DEF;SG
spiralfjær	spiralfjæra	N;DEF;SG
spiralfjær	spiralfjærer	N;NDEF;PL
mikroskopisk	mikroskopisk	ADJ;NEUT;SG
mikroskopisk	mikroskopiske	ADJ;DEF;SG+PL
fingertupp	fingertuppen	N;DEF;SG
fingertupp	fingertupper	N;NDEF;PL
fingertupp	fingertuppene	N;DEF;PL
olje	oljer	N;NDEF;PL
olje	oljene	N;DEF;PL
olje	oljen	N;DEF;SG
olje	olja	N;DEF;SG
fiskebåt	fiskebåter	N;NDEF;PL
fiskebåt	fiskebåten	N;DEF;SG
fiskebåt	fiskebåtene	N;DEF;PL
senter	senteret	N;DEF;SG
senter	sentre	N;NDEF;PL
senter	sentra	N;DEF;PL
senter	sentrene	N;DEF;PL
senter	senter	N;NDEF;PL
tankefull	tankefullt	ADJ;NEUT;SG
tankefull	tankefulle	ADJ;DEF;SG+PL
møte	møtet	N;DEF;SG
møte	møter	V;PRS
møte	møta	N;DEF;PL
møte	møtt	V.PTCP;PST
møte	møtte	V;PST
møte	møt	V;IMP
møte	møter	N;NDEF;PL
møte	møtene	N;DEF;PL
spekter	spektret	N;DEF;SG
spekter	spektra	N;DEF;PL
spekter	spektre	N;NDEF;PL
spekter	spektrene	N;DEF;PL
spekter	spekter	N;NDEF;PL
spekter	spekteret	N;DEF;SG
konvolutt	konvolutten	N;DEF;SG
konvolutt	konvolutter	N;NDEF;PL
konvolutt	konvoluttene	N;DEF;PL
isbryter	isbrytere	N;NDEF;PL
isbryter	isbryteren	N;DEF;SG
isbryter	isbryterne	N;DEF;PL
uniform	uniformen	N;DEF;SG
uniform	uniformene	N;DEF;PL
uniform	uniformer	N;NDEF;PL
single	singlen	N;DEF;SG
single	singlene	N;DEF;PL
single	singler	N;NDEF;PL
mur	murer	N;NDEF;PL
mur	muren	N;DEF;SG
mur	murene	N;DEF;PL
ministerium	ministeriene	N;DEF;PL
ministerium	ministeriet	N;DEF;SG
ministerium	ministerier	N;NDEF;PL
unødvendig	unødvendig	ADJ;NEUT;SG
unødvendig	unødvendige	ADJ;DEF;SG+PL
maje	maja	N;DEF;SG
maje	majer	N;NDEF;PL
maje	majene	N;DEF;PL
trykkoker	trykkokerne	N;DEF;PL
trykkoker	trykkokeren	N;DEF;SG
trykkoker	trykkokere	N;NDEF;PL
sørlig	sørlige	ADJ;DEF;SG+PL
sørlig	sørlig	ADJ;NEUT;SG
kamera	kameraet	N;DEF;SG
kamera	kameraene	N;DEF;PL
kamera	kameraer	N;NDEF;PL
allmenn	allment	ADJ;NEUT;SG
allmenn	allmenne	ADJ;DEF;SG+PL
øve	øvet	V;PST
øve	øver	V;PRS
øve	øvd	V.PTCP;PST
øve	øvende	V.PTCP;PRS
øve	øv	V;IMP
øve	øvet	V.PTCP;PST
øve	øvde	V;PST
elmotor	elmotorer	N;NDEF;PL
elmotor	elmotoren	N;DEF;SG
elmotor	elmotorene	N;DEF;PL
hodepine	hodepiner	N;NDEF;PL
hodepine	hodepinene	N;DEF;PL
hodepine	hodepinen	N;DEF;SG
eksoterm	eksotermt	ADJ;NEUT;SG
eksoterm	eksoterme	ADJ;DEF;SG+PL
setebelte	setebeltene	N;DEF;PL
setebelte	setebeltet	N;DEF;SG
setebelte	setebelter	N;NDEF;PL
teknologi	teknologien	N;DEF;SG
teknologi	teknologiene	N;DEF;PL
teknologi	teknologier	N;NDEF;PL
beundring	beundringen	N;DEF;SG
beundring	beundringa	N;DEF;SG
estetisk	estetisk	ADJ;NEUT;SG
estetisk	estetiske	ADJ;DEF;SG+PL
endring	endringer	N;NDEF;PL
endring	endringen	N;DEF;SG
endring	endringene	N;DEF;PL
endring	endringa	N;DEF;SG
afrikansk	afrikansk	ADJ;FEM
afrikansk	afrikanske	ADJ;DEF;SG+PL
afrikansk	afrikansk	ADJ;MASC
afrikansk	afrikansk	ADJ;NEUT
halvtime	halvtimen	N;DEF;SG
halvtime	halvtimer	N;NDEF;PL
halvtime	halvtimene	N;DEF;PL
milkshake	milkshaken	N;DEF;SG
milkshake	milkshakene	N;DEF;PL
milkshake	milkshaker	N;NDEF;PL
tegn	tegna	N;DEF;PL
tegn	tegnet	N;DEF;SG
tegn	tegn	N;NDEF;PL
migrene	migrenene	N;DEF;PL
migrene	migrener	N;NDEF;PL
migrene	migrenen	N;DEF;SG
forhugning	forhugninger	N;NDEF;PL
forhugning	forhugninga	N;DEF;SG
forhugning	forhugningen	N;DEF;SG
forhugning	forhugningene	N;DEF;PL
dagbrudd	dagbruddet	N;DEF;SG
dagbrudd	dagbrudda	N;DEF;PL
dagbrudd	dagbrudd	N;NDEF;PL
appelsin	appelsinen	N;DEF;SG
appelsin	appelsiner	N;NDEF;PL
appelsin	appelsinene	N;DEF;PL
skogbruk	skogbruket	N;DEF;SG
skogbruk	skogbrukene	N;DEF;PL
skogbruk	skogbruk	N;NDEF;PL
skogbruk	skogbruka	N;DEF;PL
spanjol	spanjolen	N;DEF;SG
spanjol	spanjolene	N;DEF;PL
spanjol	spanjoler	N;NDEF;PL
kork	korker	N;NDEF;PL
kork	korken	N;DEF;SG
kork	korkene	N;DEF;PL
hærverk	hærverkene	N;DEF;PL
hærverk	hærverk	N;NDEF;PL
hærverk	hærverker	N;NDEF;PL
hærverk	hærverket	N;DEF;SG
hærverk	hærverka	N;DEF;PL
blåbær	blåbær	N;NDEF;PL
blåbær	blåbæret	N;DEF;SG
blåbær	blåbærene	N;DEF;PL
filosofere	filosoferer	V;PRS
filosofere	filosofert	V.PTCP;PST
filosofere	filosofer	V;IMP
filosofere	filosoferte	V;PST
datasimulering	datasimuleringen	N;DEF;SG
datasimulering	datasimuleringene	N;DEF;PL
datasimulering	datasimuleringer	N;NDEF;PL
datasimulering	datasimuleringa	N;DEF;SG
mineral	mineraler	N;NDEF;PL
mineral	mineralet	N;DEF;SG
mineral	minerala	N;DEF;PL
mineral	mineral	N;NDEF;PL
mineral	mineralene	N;DEF;PL
vinge	vingen	N;DEF;SG
vinge	vinger	N;NDEF;PL
vinge	vingene	N;DEF;PL
hyperlenke	hyperlenka	N;DEF;SG
hyperlenke	hyperlenkene	N;DEF;PL
hyperlenke	hyperlenker	N;NDEF;PL
islending	islendinger	N;NDEF;PL
islending	islendingen	N;DEF;SG
islending	islendingene	N;DEF;PL
kjegle	kjegla	N;DEF;SG
kjegle	kjeglen	N;DEF;SG
kjegle	kjegler	N;NDEF;PL
kjegle	kjeglene	N;DEF;PL
tapet	tapeta	N;DEF;PL
tapet	tapeter	N;NDEF;PL
tapet	tapetet	N;DEF;SG
hydrokarbon	hydrokarboner	N;NDEF;PL
hydrokarbon	hydrokarbonet	N;DEF;SG
hydrokarbon	hydrokarbona	N;DEF;PL
hydrokarbon	hydrokarbonene	N;DEF;PL
billett	billettene	N;DEF;PL
billett	billetten	N;DEF;SG
billett	billetter	N;NDEF;PL
dirigent	dirigenten	N;DEF;SG
dirigent	dirigentene	N;DEF;PL
dirigent	dirigenter	N;NDEF;PL
flertall	flertall	N;NDEF;PL
flertall	flertallet	N;DEF;SG
flertall	flertallene	N;DEF;PL
flertall	flertalla	N;DEF;PL
forsage	forsager	V;PRS
forsage	forsaget	V;PST
forsage	forsagende	V.PTCP;PRS
revolusjonær	revolusjonære	ADJ;DEF;SG+PL
revolusjonær	revolusjonærer	N;NDEF;PL
revolusjonær	revolusjonærene	N;DEF;PL
revolusjonær	revolusjonært	ADJ;NDEF;NEUT;SG
revolusjonær	revolusjonæren	N;DEF;SG
etterligne	etterlign	V;IMP
etterligne	etterlignet	V;PST
etterligne	etterlignende	V.PTCP;PRS
etterligne	etterligna	V;PST
etterligne	etterligner	V;PRS
meteorologi	meteorologien	N;DEF;SG
produksjon	produksjoner	N;NDEF;PL
produksjon	produksjonen	N;DEF;SG
produksjon	produksjonene	N;DEF;PL
munn	munnene	N;DEF;PL
munn	munner	N;NDEF;PL
munn	munnen	N;DEF;SG
latter	latteren	N;DEF;SG
hytte	hytta	N;DEF;SG
hytte	hytter	N;NDEF;PL
hytte	hyttene	N;DEF;PL
slovakisk	slovakiske	ADJ;DEF;SG+PL
slovakisk	slovakisken	N;DEF;SG
slovakisk	slovakisk	ADJ;NEUT;SG
salto	saltoer	N;NDEF;PL
salto	saltoen	N;DEF;SG
salto	saltoene	N;DEF;PL
fotosyntese	fotosyntesen	N;DEF;SG
forurensning	forurensningene	N;DEF;PL
forurensning	forurensninga	N;DEF;SG
forurensning	forurensninger	N;NDEF;PL
forurensning	forurensningen	N;DEF;SG
langskip	langskip	N;NDEF;PL
langskip	langskipa	N;DEF;PL
langskip	langskipet	N;DEF;SG
andel	andelen	N;DEF;SG
andel	andelene	N;DEF;PL
andel	andeler	N;NDEF;PL
definisjon	definisjonene	N;DEF;PL
definisjon	definisjoner	N;NDEF;PL
definisjon	definisjonen	N;DEF;SG
kontinental	kontinentale	ADJ;DEF;SG+PL
kontinental	kontinentalt	ADJ;NEUT;SG
øyenskygge	øyenskyggen	N;DEF;SG
øyenskygge	øyenskyggene	N;DEF;PL
øyenskygge	øyenskygger	N;NDEF;PL
sink	sinket	N;DEF;SG
søvnløs	søvnløst	ADJ;NEUT;SG
søvnløs	søvnløse	ADJ;DEF;SG+PL
bauxitt	bauxitten	N;DEF;SG
velge	velger	V;PRS
velge	velg	V;IMP
velge	velgende	V.PTCP;PRS
velge	valgte	V;PST
velge	valgt	V.PTCP;PST
badeby	badebyer	N;NDEF;PL
badeby	badebyen	N;DEF;SG
badeby	badebyene	N;DEF;PL
forelder	foreldre	N;NDEF;PL
forelder	foreldra	N;DEF;PL
forelder	forelderen	N;DEF;SG
mamma	mammaer	N;NDEF;PL
mamma	mammaen	N;DEF;SG
mamma	mammaene	N;DEF;PL
landskap	landskapa	N;DEF;PL
landskap	landskap	N;NDEF;PL
landskap	landskapet	N;DEF;SG
trulig	trulige	ADJ;DEF;SG+PL
trulig	trulig	ADJ;NEUT;SG
japansk	japanske	ADJ;DEF;SG+PL
japansk	japansk	ADJ;NEUT;SG
japansk	japansken	N;DEF;SG
subtraksjon	subtraksjonen	N;DEF;SG
subtraksjon	subtraksjoner	N;NDEF;PL
subtraksjon	subtraksjonene	N;DEF;PL
misjon	misjoner	N;NDEF;PL
misjon	misjonene	N;DEF;PL
misjon	misjonen	N;DEF;SG
prosent	prosenter	N;NDEF;PL
prosent	prosenten	N;DEF;SG
prosent	prosentene	N;DEF;PL
gjerning	gjerningene	N;DEF;PL
gjerning	gjerninger	N;NDEF;PL
gjerning	gjerningen	N;DEF;SG
prosedyre	prosedyrer	N;NDEF;PL
prosedyre	prosedyrene	N;DEF;PL
prosedyre	prosedyren	N;DEF;SG
fullblodshest	fullblodshester	N;NDEF;PL
fullblodshest	fullblodshesten	N;DEF;SG
fullblodshest	fullblodshestene	N;DEF;PL
æra	æraen	N;DEF;SG
æra	æraer	N;NDEF;PL
æra	æraene	N;DEF;PL
flaggermus	flaggermusene	N;DEF;PL
flaggermus	flaggermusen	N;DEF;SG
flaggermus	flaggermusa	N;DEF;SG
flaggermus	flaggermus	N;NDEF;PL
grønnsak	grønnsaka	N;DEF;SG
grønnsak	grønnsakene	N;DEF;PL
grønnsak	grønnsaker	N;NDEF;PL
kakiplomme	kakiplommer	N;NDEF;PL
kakiplomme	kakiplomma	N;DEF;SG
kakiplomme	kakiplommen	N;DEF;SG
kakiplomme	kakiplommene	N;DEF;PL
band	banda	N;DEF;PL
band	bandet	N;DEF;SG
band	band	N;NDEF;PL
band	bandene	N;DEF;PL
glassmester	glassmestrer	N;NDEF;PL
glassmester	glassmestrene	N;DEF;PL
glassmester	glassmesteren	N;DEF;SG
flate	flater	N;NDEF;PL
flate	flata	N;DEF;SG
flate	flatene	N;DEF;PL
flate	flaten	N;DEF;SG
elektromotor	elektromotoren	N;DEF;SG
elektromotor	elektromotorene	N;DEF;PL
elektromotor	elektromotorer	N;NDEF;PL
andorraner	andorraneren	N;DEF;SG
andorraner	andorranerne	N;DEF;PL
andorraner	andorranere	N;NDEF;PL
tilgang	tilgangene	N;DEF;PL
tilgang	tilganger	N;NDEF;PL
tilgang	tilgangen	N;DEF;SG
infeksiøs	infeksiøse	ADJ;DEF;SG+PL
infeksiøs	infeksiøst	ADJ;NEUT;SG
undervurdere	undervurder	V;IMP
undervurdere	undervurderte	V;PST
undervurdere	undervurderer	V;PRS
undervurdere	undervurderende	V.PTCP;PRS
undervurdere	undervurdert	V.PTCP;PST
minske	minska	V;PST
minske	minsker	V;PRS
minske	minsk	V;IMP
fabrikant	fabrikantene	N;DEF;PL
fabrikant	fabrikanten	N;DEF;SG
fabrikant	fabrikanter	N;NDEF;PL
ending	endinga	N;DEF;SG
ending	endingene	N;DEF;PL
ending	endinger	N;NDEF;PL
oppnå	oppnå	V;IMP
oppnå	oppnådd	V.PTCP;PST
oppnå	oppnådde	V;PST
oppnå	oppnår	V;PRS
udelelig	udelelig	ADJ;NEUT;SG
udelelig	udelelige	ADJ;DEF;SG+PL
fuktighet	fuktigheten	N;DEF;SG
fuktighet	fuktigheta	N;DEF;SG
superlim	superlimet	N;DEF;SG
niese	niesen	N;DEF;SG
niese	nieser	N;NDEF;PL
niese	niesene	N;DEF;PL
fantasere	fantasert	V.PTCP;PST
fantasere	fantaserte	V;PST
fantasere	fantaserende	V.PTCP;PRS
fantasere	fantaser	V;IMP
fantasere	fantaserer	V;PRS
avgjøre	avgjorde	V;PST
avgjøre	avgjørende	V.PTCP;PRS
avgjøre	avgjør	V;IMP
avgjøre	avgjort	V.PTCP;PST
avgjøre	avgjør	V;PRS
forskjell	forskjellene	N;DEF;PL
forskjell	forskjeller	N;NDEF;PL
forskjell	forskjellen	N;DEF;SG
ønske	ønska	N;DEF;PL
ønske	ønskte	V;PST
ønske	ønsk	V;IMP
ønske	ønska	V.PTCP;PST
ønske	ønsker	N;NDEF;PL
ønske	ønsket	N;DEF;SG
ønske	ønsker	V;PRS
ønske	ønskt	V.PTCP;PST
ønske	ønskene	N;DEF;PL
barneprostitusjon	barneprostitusjonen	N;DEF;SG
amfetamin	amfetamin	N;NDEF;PL
amfetamin	amfetamina	N;DEF;PL
amfetamin	amfetaminene	N;DEF;PL
amfetamin	amfetaminet	N;DEF;SG
amfetamin	amfetaminer	N;NDEF;PL
kolposkop	kolposkoper	N;NDEF;PL
kolposkop	kolposkopa	N;DEF;PL
kolposkop	kolposkopet	N;DEF;SG
kolposkop	kolposkop	N;NDEF;PL
skaper	skaperne	N;DEF;PL
skaper	skapere	N;NDEF;PL
skaper	skaperen	N;DEF;SG
vakuum	vakuuma	N;DEF;PL
vakuum	vakuum	N;NDEF;PL
vakuum	vakuumer	N;NDEF;PL
vakuum	vakuumet	N;DEF;SG
fotballspiller	fotballspillere	N;NDEF;PL
fotballspiller	fotballspillerne	N;DEF;PL
fotballspiller	fotballspilleren	N;DEF;SG
proporsjonal	proporsjonalt	ADJ;NEUT;SG
proporsjonal	proporsjonale	ADJ;DEF;SG+PL
angstbiting	angstbitingen	N;DEF;SG
angstbiting	angstbitinger	N;NDEF;PL
angstbiting	angstbitingene	N;DEF;PL
angstbiting	angstbitinga	N;DEF;SG
pedo	pedoen	N;DEF;SG
pedo	pedoene	N;DEF;PL
pedo	pedoer	N;NDEF;PL
overfladisk	overfladiske	ADJ;DEF;SG+PL
overfladisk	overfladisk	ADJ;NEUT;SG
modellfly	modellflyene	N;DEF;PL
modellfly	modellfly	N;NDEF;PL
modellfly	modellflyet	N;DEF;SG
modellfly	modellflya	N;DEF;PL
fluidmekanikk	fluidmekanikken	N;DEF;SG
utropstegn	utropstegn	N;NDEF;PL
utropstegn	utropstegnene	N;DEF;PL
utropstegn	utropstegnet	N;DEF;SG
spark	sparkene	N;DEF;PL
spark	spark	N;NDEF;PL
spark	sparket	N;DEF;SG
draft	draftet	N;DEF;SG
draft	draftene	N;DEF;PL
draft	draft	N;NDEF;PL
draft	drafta	N;DEF;PL
draft	drafter	N;NDEF;PL
sekund	sekundene	N;DEF;PL
sekund	sekundet	N;DEF;SG
sekund	sekund	N;NDEF;PL
sekund	sekunder	N;NDEF;PL
lisens	lisensene	N;DEF;PL
lisens	lisensen	N;DEF;SG
lisens	lisenser	N;NDEF;PL
inngang	inngangene	N;DEF;PL
inngang	innganger	N;NDEF;PL
inngang	inngangen	N;DEF;SG
karbonmonoksid	karbonmonoksidet	N;DEF;SG
istapp	istappene	N;DEF;PL
istapp	istapper	N;NDEF;PL
istapp	istappen	N;DEF;SG
verktøy	verktøyene	N;DEF;PL
verktøy	verktøyer	N;NDEF;PL
verktøy	verktøyet	N;DEF;SG
verktøy	verktøy	N;NDEF;PL
hue	huer	N;NDEF;PL
hue	huene	N;DEF;PL
hue	hua	N;DEF;SG
hue	huen	N;DEF;SG
bakteriologi	bakteriologien	N;DEF;SG
barn	barn	N;NDEF;PL
barn	barnene	N;DEF;PL
barn	barnet	N;DEF;SG
barn	barna	N;DEF;PL
sersjant	sersjantene	N;DEF;PL
sersjant	sersjanten	N;DEF;SG
sersjant	sersjanter	N;NDEF;PL
uro	uroa	N;DEF;SG
uro	uroene	N;DEF;PL
uro	uroer	N;NDEF;PL
pandemi	pandemiene	N;DEF;PL
pandemi	pandemier	N;NDEF;PL
pandemi	pandemien	N;DEF;SG
påhengsmotor	påhengsmotoren	N;DEF;SG
påhengsmotor	påhengsmotorer	N;NDEF;PL
påhengsmotor	påhengsmotorene	N;DEF;PL
skilletegn	skilletegnet	N;DEF;SG
skilletegn	skilletegnene	N;DEF;PL
skilletegn	skilletegn	N;NDEF;PL
massakre	massakrene	N;DEF;PL
massakre	massakren	N;DEF;SG
massakre	massakrer	N;NDEF;PL
kirurgisk	kirurgiske	ADJ;DEF;SG+PL
kirurgisk	kirurgisk	ADJ;NEUT;SG
merkelig	merkelig	ADJ;NEUT;SG
merkelig	merkelige	ADJ;DEF;SG+PL
grafisk	grafiske	ADJ;DEF;SG+PL
grafisk	grafisk	ADJ;NEUT;SG
stratenrøver	stratenrøverne	N;DEF;PL
stratenrøver	stratenrøvere	N;NDEF;PL
stratenrøver	stratenrøveren	N;DEF;SG
merr	merrene	N;DEF;PL
merr	merra	N;DEF;SG
merr	merrer	N;NDEF;PL
yoghurt	yoghurten	N;DEF;SG
yoghurt	yoghurtene	N;DEF;PL
yoghurt	yoghurter	N;NDEF;PL
rødhet	rødheta	N;DEF;SG
låne	lånte	V;PST
låne	lånende	V.PTCP;PRS
låne	lånt	V.PTCP;PST
låne	lån	V;IMP
låne	låner	V;PRS
journalist	journalisten	N;DEF;SG
journalist	journalistene	N;DEF;PL
journalist	journalister	N;NDEF;PL
gummi	gummiene	N;DEF;PL
gummi	gummier	N;NDEF;PL
gummi	gummien	N;DEF;SG
rogn	rogner	N;NDEF;PL
rogn	rognene	N;DEF;PL
rogn	rogna	N;DEF;SG
rogn	rognen	N;DEF;SG
kloster	klostre	N;NDEF;PL
kloster	klosteret	N;DEF;SG
kloster	klostrene	N;DEF;PL
kloster	klostret	N;DEF;SG
flis	flisen	N;DEF;SG
flis	fliser	N;NDEF;PL
flis	flisene	N;DEF;PL
flis	flisa	N;DEF;SG
matforgiftning	matforgiftninga	N;DEF;SG
matforgiftning	matforgiftninger	N;NDEF;PL
matforgiftning	matforgiftningene	N;DEF;PL
afrikaner	afrikanerne	N;DEF;PL
afrikaner	afrikaneren	N;DEF;SG
afrikaner	afrikanere	N;NDEF;PL
hundredel	hundredeler	N;NDEF;PL
hundredel	hundredelen	N;DEF;SG
hundredel	hundredelene	N;DEF;PL
ghaneser	ghaneserne	N;DEF;PL
ghaneser	ghaneseren	N;DEF;SG
ghaneser	ghanesere	N;NDEF;PL
nyzealender	nyzealenderne	N;DEF;PL
nyzealender	nyzealendere	N;NDEF;PL
nyzealender	nyzealenderen	N;DEF;SG
sag	saga	N;DEF;SG
sag	sager	N;NDEF;PL
sag	sagene	N;DEF;PL
sag	sagen	N;DEF;SG
krystallklar	krystallklart	ADJ;NEUT;SG
krystallklar	krystallklare	ADJ;DEF;SG+PL
mjølk	mjølken	N;DEF;SG
unaturlig	unaturlig	ADJ;NEUT;SG
unaturlig	unaturlige	ADJ;DEF;SG+PL
svigerfar	svigerfedre	N;NDEF;PL
svigerfar	svigerfaren	N;DEF;SG
svigerfar	svigerfedrene	N;DEF;PL
kassett	kassetten	N;DEF;SG
kassett	kassetter	N;NDEF;PL
kassett	kassettene	N;DEF;PL
rabarbra	rabarbraen	N;DEF;SG
rabarbra	rabarbraer	N;NDEF;PL
rabarbra	rabarbraene	N;DEF;PL
sopp	soppen	N;DEF;SG
sopp	soppene	N;DEF;PL
sopp	sopper	N;NDEF;PL
tekopp	tekopper	N;NDEF;PL
tekopp	tekoppen	N;DEF;SG
tekopp	tekoppene	N;DEF;PL
sengetid	sengetida	N;DEF;SG
sengetid	sengetider	N;NDEF;PL
sengetid	sengetidene	N;DEF;PL
sengetid	sengetiden	N;DEF;SG
vaffel	vafler	N;NDEF;PL
vaffel	vaflene	N;DEF;PL
vaffel	vaffelen	N;DEF;SG
diameter	diametre	N;NDEF;PL
diameter	diameterne	N;DEF;PL
diameter	diameteren	N;DEF;SG
diameter	diametrene	N;DEF;PL
turve	tuevte	V;PST
turve	turv	V;IMP
turve	turvt	V.PTCP;PST
turve	tarv	V;PRS
lukte	lukter	V;PRS
lukte	luktende	V.PTCP;PRS
lukte	lukt	V;IMP
lukte	lukta	V;PST
lukte	luktet	V;PST
kvadratrot	kvadratroten	N;DEF;SG
kvadratrot	kvadratrøtter	N;NDEF;PL
kvadratrot	kvadratrøttene	N;DEF;PL
kvadratrot	kvadratrota	N;DEF;SG
bevisst	bevisste	ADJ;DEF;SG+PL
bevisst	bevisst	ADJ;NEUT;SG
samtale	samtalen	N;DEF;SG
samtale	samtaler	N;NDEF;PL
samtale	samtalene	N;DEF;PL
tjener	tjeneren	N;DEF;SG
tjener	tjenerne	N;DEF;PL
tjener	tjenere	N;NDEF;PL
kineser	kineserne	N;DEF;PL
kineser	kinesere	N;NDEF;PL
kineser	kineseren	N;DEF;SG
kuwaiter	kuwaiterne	N;DEF;PL
kuwaiter	kuwaitere	N;NDEF;PL
kuwaiter	kuwaiteren	N;DEF;SG
sjettedel	sjettedeler	N;NDEF;PL
sjettedel	sjettedelene	N;DEF;PL
sjettedel	sjettedelen	N;DEF;SG
morgenkåpe	morgenkåper	N;NDEF;PL
morgenkåpe	morgenkåpene	N;DEF;PL
morgenkåpe	morgenkåpa	N;DEF;SG
kroat	kroatene	N;DEF;PL
kroat	kroater	N;NDEF;PL
kroat	kroaten	N;DEF;SG
verdensrekord	verdensrekorder	N;NDEF;PL
verdensrekord	verdensrekorden	N;DEF;SG
verdensrekord	verdensrekordene	N;DEF;PL
lineær	lineært	ADJ;NEUT;SG
lineær	lineære	ADJ;DEF;SG+PL
versjon	versjonen	N;DEF;SG
versjon	versjonene	N;DEF;PL
versjon	versjoner	N;NDEF;PL
sønn	sønnene	N;DEF;PL
sønn	sønner	N;NDEF;PL
sønn	sønnen	N;DEF;SG
rokke	rokka	N;DEF;SG
rokke	rokker	N;NDEF;PL
rokke	rokkene	N;DEF;PL
rokke	rokken	N;DEF;SG
relasjon	relasjoner	N;NDEF;PL
relasjon	relasjonene	N;DEF;PL
relasjon	relasjonen	N;DEF;SG
slette	sletter	N;NDEF;PL
slette	slettene	N;DEF;PL
slette	sletta	N;DEF;SG
krangel	krangler	N;NDEF;PL
krangel	kranglene	N;DEF;PL
krangel	krangelen	N;DEF;SG
rekord	rekorden	N;DEF;SG
rekord	rekordene	N;DEF;PL
rekord	rekorder	N;NDEF;PL
rør	røra	N;DEF;PL
rør	rør	N;NDEF;PL
rør	røret	N;DEF;SG
vits	vitsene	N;DEF;PL
vits	vitser	N;NDEF;PL
vits	vitsen	N;DEF;SG
par	paret	N;DEF;SG
par	parene	N;DEF;PL
par	par	N;NDEF;PL
par	para	N;DEF;PL
glorifisere	glorifiserte	V;PST
glorifisere	glorifiserer	V;PRS
glorifisere	glorifisert	V.PTCP;PST
glorifisere	glorifiser	V;IMP
nøkkel	nøklene	N;DEF;PL
nøkkel	nøkler	N;NDEF;PL
nøkkel	nøkkelen	N;DEF;SG
hertuginne	hertuginner	N;NDEF;PL
hertuginne	hertuginnen	N;DEF;SG
hertuginne	hertuginnene	N;DEF;PL
hertuginne	hertuginna	N;DEF;SG
skiftenøkkel	skiftenøklene	N;DEF;PL
skiftenøkkel	skiftenøkler	N;NDEF;PL
skiftenøkkel	skiftenøkkelen	N;DEF;SG
sosialisme	sosialismen	N;DEF;SG
dårlig	dårlige	ADJ;PL
dårlig	dårligst	ADJ;SPRL
dårlig	dårligere	ADJ;CMPR
pluskvamperfektum	pluskvamperfektumen	N;DEF;SG
pluskvamperfektum	pluskvamperfektumer	N;NDEF;PL
pluskvamperfektum	pluskvamperfektumene	N;DEF;PL
svigerdatter	svigerdøtre	N;NDEF;PL
svigerdatter	svigerdatteren	N;DEF;SG
svigerdatter	svigerdøtrene	N;DEF;PL
reportasje	reportasjen	N;DEF;SG
reportasje	reportasjer	N;NDEF;PL
reportasje	reportasjene	N;DEF;PL
svovel	svovelet	N;DEF;SG
svanger	svangert	ADJ;NEUT;SG
svanger	svangre	ADJ;DEF;SG+PL
varsel	varsel	N;NDEF;PL
varsel	varselet	N;DEF;SG
varsel	varsla	N;DEF;PL
varsel	varsler	N;NDEF;PL
varsel	varslene	N;DEF;PL
millimeter	millimeteren	N;DEF;SG
millimeter	millimeterne	N;DEF;PL
millimeter	millimeter	N;NDEF;PL
hypnotisme	hypnotismen	N;DEF;SG
anklage	anklag	V;IMP
anklage	anklaget	V.PTCP;PST
anklage	anklagende	V.PTCP;PRS
anklage	anklager	V;PRS
anklage	anklagde	V;PST
anklage	anklaga	V;PST
profesjon	profesjonene	N;DEF;PL
profesjon	profesjoner	N;NDEF;PL
profesjon	profesjonen	N;DEF;SG
lenestol	lenestolene	N;DEF;PL
lenestol	lenestoler	N;NDEF;PL
lenestol	lenestolen	N;DEF;SG
eie	eiet	V;PST
eie	ei	V;IMP
eie	eid	V.PTCP;PST
eie	åtte	V;PST
eie	eier	V;PRS
eie	ått	V.PTCP;PST
strømpebukse	strømpebukser	N;NDEF;PL
strømpebukse	strømpebuksen	N;DEF;SG
strømpebukse	strømpebuksene	N;DEF;PL
syn	synene	N;DEF;PL
syn	syner	N;NDEF;PL
syn	syne	V;GEN
syn	synet	N;DEF;SG
prisbevisst	prisbevisste	ADJ;DEF;SG+PL
prisbevisst	prisbevisst	ADJ;NEUT;SG
referanse	referansen	N;DEF;SG
referanse	referansene	N;DEF;PL
referanse	referanser	N;NDEF;PL
kjøtt	kjøttet	N;DEF;SG
hekk	hekkene	N;DEF;PL
hekk	hekker	N;NDEF;PL
hekk	hekken	N;DEF;SG
danser	dansere	N;NDEF;PL
danser	danseren	N;DEF;SG
danser	danserne	N;DEF;PL
pasient	pasientene	N;DEF;PL
pasient	pasienten	N;DEF;SG
pasient	pasienter	N;NDEF;PL
tema	temaene	N;DEF;PL
tema	tema	N;NDEF;PL
tema	temaet	N;DEF;SG
tema	temaer	N;NDEF;PL
middag	middager	N;NDEF;PL
middag	middagene	N;DEF;PL
middag	middagen	N;DEF;SG
optimist	optimister	N;NDEF;PL
optimist	optimistene	N;DEF;PL
optimist	optimisten	N;DEF;SG
diskotek	diskoteker	N;NDEF;PL
diskotek	diskoteka	N;DEF;PL
diskotek	diskoteket	N;DEF;SG
kryss	krysset	N;DEF;SG
kryss	kryssene	N;DEF;PL
kryss	kryss	N;NDEF;PL
periode	perioden	N;DEF;SG
periode	perioder	N;NDEF;PL
periode	periodene	N;DEF;PL
gigantisk	gigantiske	ADJ;DEF;SG+PL
gigantisk	gigantisk	ADJ;NEUT;SG
hengekøye	hengekøyer	N;NDEF;PL
hengekøye	hengekøya	N;DEF;SG
hengekøye	hengekøyen	N;DEF;SG
hengekøye	hengekøyene	N;DEF;PL
kostbar	kostbart	ADJ;NEUT;SG
kostbar	kostbare	ADJ;DEF;SG+PL
liv	liva	N;DEF;PL
liv	livene	N;DEF;PL
liv	liv	N;NDEF;PL
liv	livet	N;DEF;SG
høflig	høflige	ADJ;DEF;SG+PL
høflig	høfligst	ADJ;SPRL;NDEF
høflig	høfligere	ADJ;CMPR
høflig	høflig	ADJ;NEUT;SG
høflig	høfligste	ADJ;SPRL;DEF
slovak	slovaker	N;NDEF;PL
slovak	slovakene	N;DEF;PL
slovak	slovaken	N;DEF;SG
politiker	politikere	N;NDEF;PL
politiker	politikeren	N;DEF;SG
politiker	politikerne	N;DEF;PL
glemme	glemmer	V;PRS
glemme	glemt	V.PTCP;PST
glemme	glem	V;IMP
glemme	glemte	V;PST
septisk	septisk	ADJ;NEUT;SG
septisk	septiske	ADJ;DEF;SG+PL
landemerke	landemerket	N;DEF;SG
landemerke	landemerker	N;NDEF;PL
landemerke	landemerka	N;DEF;PL
landemerke	landemerkene	N;DEF;PL
bygning	bygninga	N;DEF;SG
bygning	bygninger	N;NDEF;PL
bygning	bygningene	N;DEF;PL
tidlig	tidligst	ADJ;SPRL;NDEF
tidlig	tidlig	ADJ;NEUT;SG
tidlig	tidligere	ADJ;CMPR
tidlig	tidligste	ADJ;SPRL;DEF
tidlig	tidlige	ADJ;DEF;SG+PL
kråke	kråkene	N;DEF;PL
kråke	kråken	N;DEF;SG
kråke	kråker	N;NDEF;PL
kråke	kråka	N;DEF;SG
premie	premier	N;NDEF;PL
premie	premiene	N;DEF;PL
premie	premien	N;DEF;SG
utgift	utgiften	N;DEF;SG
utgift	utgiftene	N;DEF;PL
utgift	utgifter	N;NDEF;PL
skulderveske	skulderveskene	N;DEF;PL
skulderveske	skuldervesker	N;NDEF;PL
skulderveske	skuldervesken	N;DEF;SG
karaffel	karaffelen	N;DEF;SG
karaffel	karaflene	N;DEF;PL
karaffel	karafler	N;NDEF;PL
missil	missil	N;NDEF;PL
missil	missilet	N;DEF;SG
missil	missilene	N;DEF;PL
rype	rypen	N;DEF;SG
rype	rypene	N;DEF;PL
rype	ryper	N;NDEF;PL
rype	rypa	N;DEF;SG
relativitet	relativiteten	N;DEF;SG
desimalkomma	desimalkommaene	N;DEF;PL
desimalkomma	desimalkommaet	N;DEF;SG
desimalkomma	desimalkomma	N;NDEF;PL
tegning	tegninger	N;NDEF;PL
tegning	tegningene	N;DEF;PL
tegning	tegningen	N;DEF;SG
sommer	sommere	N;NDEF;PL
sommer	sommerne	N;DEF;PL
sommer	sommeren	N;DEF;SG
sommer	somrer	N;NDEF;PL
sommer	somrene	N;DEF;PL
osean	oseana	N;DEF;PL
osean	oseanet	N;DEF;SG
osean	osean	N;NDEF;PL
nigerer	nigereren	N;DEF;SG
nigerer	nigerere	N;NDEF;PL
nigerer	nigererne	N;DEF;PL
idrett	idretter	N;NDEF;PL
idrett	idrettene	N;DEF;PL
idrett	idretten	N;DEF;SG
bringe	bringen	N;DEF;SG
bringe	bringer	N;NDEF;PL
bringe	bringene	N;DEF;PL
enkel	enklere	ADJ;CMPR
enkel	enklest	ADJ;SPRL;NDEF
enkel	enkle	ADJ;DEF;SG+PL
enkel	enkelt	ADJ;NEUT;SG
enkel	enkleste	ADJ;SPRL;DEF
umulig	umulige	ADJ;DEF;SG+PL
umulig	umulig	ADJ;NEUT;SG
prostituert	prostituert	ADJ;NEUT;SG
prostituert	prostituerte	ADJ;DEF;SG+PL
allé	alléene	N;DEF;PL
allé	alleen	N;DEF;SG
allé	alleer	N;NDEF;PL
allé	alléer	N;NDEF;PL
allé	alleene	N;DEF;PL
støttann	støttenner	N;NDEF;PL
støttann	støttanna	N;DEF;SG
støttann	støttennene	N;DEF;PL
næringsstoff	næringsstoff	N;NDEF;PL
næringsstoff	næringsstoffene	N;DEF;PL
næringsstoff	næringsstoffet	N;DEF;SG
kulehull	kulehullene	N;DEF;PL
kulehull	kulehull	N;NDEF;PL
kulehull	kulehullet	N;DEF;SG
kulehull	kulehuller	N;NDEF;PL
maksimere	maksimerende	V.PTCP;PRS
maksimere	maksimer	V;IMP
maksimere	maksimert	V.PTCP;PST
maksimere	maksimerer	V;PRS
maksimere	maksimerte	V;PST
formalisere	formaliserte	V;PST
formalisere	formalisert	V.PTCP;PST
formalisere	formaliser	V;IMP
formalisere	formaliserer	V;PRS
trofé	troféa	N;DEF;PL
trofé	trofé	N;NDEF;PL
trofé	troféen	N;DEF;SG
trofé	trofeen	N;DEF;SG
trofé	trofeer	N;NDEF;PL
trofé	troféer	N;NDEF;PL
trofé	troféet	N;DEF;SG
strekke	strukket	V.PTCP;PST
strekke	strekte	V;PST
strekke	strekk	V;IMP
strekke	strekker	V;PRS
strekke	strekkende	V.PTCP;PRS
opprettholde	opprettholdt	V;PST
opprettholde	oppretthold	V;IMP
opprettholde	opprettholder	V;PRS
opprettholde	opprettholdende	V.PTCP;PRS
uløst	uløste	ADJ;DEF;SG+PL
uløst	uløst	ADJ;NEUT;SG
muslim	muslimer	N;NDEF;PL
muslim	muslimene	N;DEF;PL
muslim	muslimen	N;DEF;SG
umyndig	umyndige	ADJ;DEF;SG+PL
umyndig	umyndig	ADJ;NEUT;SG
renessanse	renessanser	N;NDEF;PL
renessanse	renessansene	N;DEF;PL
renessanse	renessansen	N;DEF;SG
ror	ror	N;NDEF;PL
ror	rora	N;DEF;PL
ror	roret	N;DEF;SG
etiopier	etiopierne	N;DEF;PL
etiopier	etiopieren	N;DEF;SG
etiopier	etiopiere	N;NDEF;PL
sten	stenen	N;DEF;SG
sten	stenene	N;DEF;PL
sten	stener	N;NDEF;PL
tam	tamme	ADJ;DEF;SG+PL
tam	tamt	ADJ;NEUT;SG
umenneskelig	umenneskelige	ADJ;DEF;SG+PL
umenneskelig	umenneskelig	ADJ;NEUT;SG
brukergrensesnitt	brukergrensesnitt	N;NDEF;PL
brukergrensesnitt	brukergrensesnittet	N;DEF;SG
brukergrensesnitt	brukergrensesnittene	N;DEF;PL
brukergrensesnitt	brukergrensesnitta	N;DEF;PL
aspekt	aspekten	N;DEF;SG
aspekt	aspekta	N;DEF;PL
aspekt	aspekter	N;NDEF;PL
aspekt	aspektet	N;DEF;SG
ledelse	ledelser	N;NDEF;PL
ledelse	ledelsen	N;DEF;SG
ledelse	ledelsene	N;DEF;PL
avtale	avtaler	N;NDEF;PL
avtale	avtalen	N;DEF;SG
avtale	avtalene	N;DEF;PL
eufemistisk	eufemistisk	ADJ;NEUT;SG
eufemistisk	eufemistiske	ADJ;DEF;SG+PL
mikser	mikserne	N;DEF;PL
mikser	mikseren	N;DEF;SG
mikser	miksere	N;NDEF;PL
øyenvipp	øyenvippene	N;DEF;PL
øyenvipp	øyenvipper	N;NDEF;PL
øyenvipp	øyenvippen	N;DEF;SG
leveranse	leveransen	N;DEF;SG
leveranse	leveransene	N;DEF;PL
leveranse	leveranser	N;NDEF;PL
følsom	følsomt	ADJ;NEUT;SG
følsom	følsomme	ADJ;DEF;SG+PL
omslag	omslagene	N;DEF;PL
omslag	omslag	N;NDEF;PL
omslag	omslaget	N;DEF;SG
omslag	omslaga	N;DEF;PL
dansegulv	dansegulvene	N;DEF;PL
dansegulv	dansegulv	N;NDEF;PL
dansegulv	dansegulvet	N;DEF;SG
teleskopisk	teleskopisk	ADJ;NEUT;SG
teleskopisk	teleskopiske	ADJ;DEF;SG+PL
hockey	hockeyen	N;DEF;SG
voldsom	voldsomt	ADJ;NEUT;SG
voldsom	voldsomme	ADJ;DEF;SG+PL
reform	reformen	N;DEF;SG
reform	reformene	N;DEF;PL
reform	reformer	N;NDEF;PL
annen	andre	ADJ;DEF
annen	annet	ADJ;NEUT
annen	andre	ADJ;PL
annen	anna	ADJ;FEM
hellighet	helligheten	N;DEF;SG
hellighet	helligheta	N;DEF;SG
encyklopedi	encyklopedier	N;NDEF;PL
encyklopedi	encyklopediene	N;DEF;PL
encyklopedi	encyklopedien	N;DEF;SG
vulkan	vulkaner	N;NDEF;PL
vulkan	vulkanene	N;DEF;PL
vulkan	vulkanen	N;DEF;SG
takke	takk	V;IMP
takke	takka	V;PST
takke	takker	V;PRS
kapitél	kapitélene	N;DEF;PL
kapitél	kapitéler	N;NDEF;PL
kapitél	kapitélet	N;DEF;SG
kapitél	kapitéla	N;DEF;PL
fremgang	fremgangen	N;DEF;SG
fremgang	fremganger	N;NDEF;PL
fremgang	fremgangene	N;DEF;PL
smakløs	smakløst	ADJ;NEUT;SG
smakløs	smakløse	ADJ;DEF;SG
tilstrekkelig	tilstrekkelig	ADJ;NEUT;SG
tilstrekkelig	tilstrekkelige	ADJ;DEF;SG+PL
viser	viserne	N;DEF;PL
viser	viseren	N;DEF;SG
viser	visere	N;NDEF;PL
pigment	pigmentet	N;DEF;SG
pigment	pigmenta	N;DEF;PL
pigment	pigment	N;NDEF;PL
pigment	pigmentene	N;DEF;PL
pigment	pigmenter	N;NDEF;PL
avis	avisa	N;DEF;SG
avis	avisene	N;DEF;PL
avis	aviser	N;NDEF;PL
strekk	strekk	N;NDEF;PL
strekk	strekken	N;DEF;SG
strekk	strekka	N;DEF;PL
strekk	strekker	N;NDEF;PL
strekk	strekket	N;DEF;SG
strekk	strekkene	N;DEF;PL
