chayndi	chayndi	V;PRS
chayndi	gachayndi	V;PST
chayndi	nachayndi	V;FUT
gaah	gagaah	V;PST
gaah	gaah	V;PRS
gaah	nagaah	V;FUT
haagn	haagn	V;PRS
haagn	nahaagn	V;FUT
haagn	gahaagn	V;PST
ma'A	nama'A	V;FUT
ma'A	ma'A	V;PRS
ma'A	gama'A	V;PST
gnaah	nagnaah	V;FUT
gnaah	gnaah	V;PRS
gnaah	gagnaah	V;PST
fayri	fayri	V;PRS
fayri	nafayri	V;FUT
fayri	gafayri	V;PST
